### PR TITLE
Fix NetworkOnMainThreadException on HybridFile.getUsableSpace() and HybridFileParcelable.isDirectory()

### LINKED ISSUE #3982: ```NetworkOnMainThreadException``` on ```HybridFile#getUsableSpace```
## Issue explanation (write below this line)

attempting to cut or copy a file from internal storage to smb share folder
over wifi network to nas server (on different subnet) (has always worked
with the same .pdf files similarly named in the past)

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.9
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux
samsung/c2quew/c2q:13/TP1A.220624.014/N986U1UEU5HWHA:user/release-keys 13 -
33
* __Device:__ c2q
* __Model:__ SM-N986U1
* __Product:__ c2quew
<details><summary><b>Crash log </b></summary><p>

```
android.os.NetworkOnMainThreadException
at
android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
at java.net.SocketOutputStream.write(SocketOutputStream.java:156)
at jcifs.smb.SmbTransportImpl.doSend(SmbTransportImpl.java:914)
at jcifs.util.transport.Transport.doSend(Transport.java:276)
at jcifs.util.transport.Transport.sendrecv(Transport.java:215)
at jcifs.smb.SmbTransportImpl.sendrecv(SmbTransportImpl.java:1025)
at jcifs.smb.SmbTransportImpl.send(SmbTransportImpl.java:1549)
at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:409)
at jcifs.smb.SmbTreeImpl.send(SmbTreeImpl.java:472)
at jcifs.smb.SmbTreeConnection.send0(SmbTreeConnection.java:404)
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:318)
at jcifs.smb.SmbTreeConnection.send(SmbTreeConnection.java:298)
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:130)
at jcifs.smb.SmbTreeHandleImpl.send(SmbTreeHandleImpl.java:117)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1761)
at jcifs.smb.SmbFile.withOpen(SmbFile.java:1730)
at jcifs.smb.SmbFile.queryFSInformation(SmbFile.java:1626)
at jcifs.smb.SmbFile.fetchAllocationInfo(SmbFile.java:1602)
at jcifs.smb.SmbFile.getDiskFreeSpace(SmbFile.java:1581)
at
com.amaze.filemanager.filesystem.HybridFile.getUsableSpace(HybridFile.java:784)
at
com.amaze.filemanager.asynchronous.asynctasks.movecopy.PreparePasteTask.execute(PreparePasteTask.kt:149)
at
com.amaze.filemanager.filesystem.PasteHelper$2.lambda$onSuccess$0(PasteHelper.java:171)
at
com.amaze.filemanager.filesystem.PasteHelper$2.$r8$lambda$WCIV1v6PgmNC7uG8zXvW9OLjAmQ(Unknown
Source:0)
at
com.amaze.filemanager.filesystem.PasteHelper$2$$ExternalSyntheticLambda0.run(Unknown
Source:2)
at
com.amaze.filemanager.utils.Utils.lambda$showCutCopySnackBar$1(Utils.java:371)
at
com.amaze.filemanager.utils.Utils.$r8$lambda$4idEvFLOs3eF7-x6YKX_WvNl_IQ(Unknown
Source:0)
at
com.amaze.filemanager.utils.Utils$$ExternalSyntheticLambda2.onClick(Unknown
Source:2)
at android.view.View.performClick(View.java:7892)
at android.widget.TextView.performClick(TextView.java:16220)
at android.view.View.performClickInternal(View.java:7869)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30891)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8762)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by TranceLove**
## Description

- Fix `SmbFile.getDiskSpace()` was not wrapped with RxJava in `HybridFile.getUsableSpace()` for network calls
- Added `HybridFileParcelable.isDirectory(Context)` that made copy and paste remote folders unnecessary long, especially when remote is SSH server

#### Issue tracker   
Fixes #3982

#### Manual tests
- [x] Done  
  
Device:
- Pixel 5 emulator running Android 11
- Fairphone 3 running LineageOS 20 (13)

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/filesystem/HybridFileParcelable.java [hunk 1]
```diff
@@ -147,6 +147,11 @@ public boolean isDirectory() {
     return isDirectory;
   }
 
+  @Override
+  public boolean isDirectory(Context context) {
+    return isDirectory;
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/HybridFileParcelable.java:152]: this may lead to issues, can you just return isDirectory only in case of SMB if you've tested it properly.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Comment by TranceLove** [comment]
Added an alert dialog which will pop up when attempt to load SMB server root without credentials failed.

Per Samba docs it indicates it's a good practice to restrict unauthenticated access to SMB server root, or in other words, the `IPC$` share. But it's decent that some feedback to user is necessary.

**Review by VishalNehra — APPROVED** [review]
