### PR TITLE
Fixes #3790

### LINKED ISSUE #3790: "ADD SHORTCUT" COMMAND DISPLAYS THE NAME OF THE PATH INSTEAD OF THE NAME OF THE FILE ITSELF
**Describe the bug**
When I create a shortcut to the main page, it doesn't show the name of the file, it shows the path instead

**To Reproduce**
1. Select a file from the File Manager
2. Click on 'Add Shortcut'
3. Go to the Main page of your phone

**Expected behavior**
I want the name of the file to be displayed as the name of the shortcut, not the path!

**Screenshots**

**Smartphone:**
 - Device: Xiaomi Redmi Note 9 Pro Global
 - OS: [MIUI Global 14.0.4] Android 12
 - Version: [v.3.8.4]

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   

Fixes #3790

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by TranceLove — APPROVED** [review]
Looks decent

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 1]
```diff
@@ -444,14 +444,16 @@ public static void addShortcut(
     shortcutIntent.setAction(Intent.ACTION_MAIN);
     shortcutIntent.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP);
 
+    String fileName = new File(path.desc).getName();
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java:447]: Can't use `path.title`?

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]
