### PR TITLE
FAB click listener migration

### LINKED ISSUE #2386: Crash: CompressedExplorerFragment casted to TabFragment
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux
HUAWEI/DRA-LX5/HWDRA-MG:8.1.0/HUAWEIDRA-LX5/1.0.0.146(C16):user/release-keys
8.1.0 - 27
* __Device:__ HWDRA-MG
* __Model:__ DRA-LX5
* __Product:__ DRA-LX5
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException:
com.amaze.filemanager.ui.fragments.CompressedExplorerFragment cannot be
cast to com.amaze.filemanager.ui.fragments.TabFragment
at
com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2036)
at
com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
at
com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
at android.view.View.performClick(View.java:6367)
at android.view.View$PerformClick.run(View.java:25040)
at android.os.Handler.handleCallback(Handler.java:795)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:6861)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

### LINKED ISSUE #2637: Crash on ProcessViewerFragment cannot be cast to TabFragment
## Issue explanation (write below this line)

Have in the file process area (Move file) tries to create a new folder.

## Exception
* __App Name:__ Amaze Dateimanager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.0
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 10 - 29
* __Device:__ FP3
* __Model:__ FP3
* __Product:__ FP3
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: com.amaze.filemanager.ui.fragments.ProcessViewerFragment cannot be cast to com.amaze.filemanager.ui.fragments.TabFragment
	at com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2172)
	at com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
	at com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

### LINKED ISSUE #2984: Unable to find current fragment when performing fab action
## Exception
* App Name: Panel de navegación de ejemplo
* Package: com.amaze.filemanager
* Version: 3.6.5
* User Action: UI Error
* Request: Application crash
* OS: Linux Nokia/Wolverine_00WW/WVR_sprout:11/RP1A.200720.011/00WW_2_230:user/release-keys 11 - 30
* Device: WVR_sprout
* Model: Nokia 2.4
* Product: Wolverine_00WW
<details><summary><b>Crash log </b></summary><p>

java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.Fragment com.amaze.filemanager.ui.fragments.TabFragment.getCurrentTabFragment()' on a null object reference
 at com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2260)
 at com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
 at com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
 at android.view.View.performClick(View.java:7455)
 at android.view.View.performClickInternal(View.java:7428)
 at android.view.View.access$3600(View.java:813)
 at android.view.View$PerformClick.run(View.java:28495)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7700)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

</details>
<hr>

Reporter: EmmanuelMess

### LINKED ISSUE #3785: `ClassCastException` on `MainActivity$FabActionListener#onActionSelected`
## Exception
* App Name: Amaze File Manager
* Package: com.amaze.filemanager
* Version: 3.8.5
* User Action: UI Error
* Request: Application crash
* OS: Linux samsung/a12nnxx/a12:12/SP1A.210812.016/A125FXXU2CVH1:user/release-keys 12 - 31
* Device: a12
* Model: SM-A125F
* Product: a12nnxx
<details><summary><b>Crash log </b></summary><p>

java.lang.ClassCastException: com.amaze.filemanager.ui.fragments.AppsListFragment cannot be cast to com.amaze.filemanager.ui.fragments.TabFragment
 at com.amaze.filemanager.ui.activities.MainActivity$FabActionListener.onActionSelected(MainActivity.java:2378)
 at com.leinardi.android.speeddial.SpeedDialView$1.onActionSelected(SpeedDialView.java:108)
 at com.leinardi.android.speeddial.FabWithLabelView$2.onClick(FabWithLabelView.java:214)
 at android.view.View.performClick(View.java:7792)
 at android.view.View.performClickInternal(View.java:7769)
 at android.view.View.access$3800(View.java:910)
 at android.view.View$PerformClick.run(View.java:30218)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8663)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

</details>
<hr>

Reporter: shadow_082

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   

- Fixes #3785 
- Fixes #2984
- Fixes #2637
- Fixes #2386

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

(moved the class to a lambda class to avoid the cause of a potential memory leak, CMIIW)

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java [hunk 1]
```diff
@@ -1785,7 +1785,34 @@ public void initializeFabActionViews() {
...
+          int id = actionItem.getId();
+
+          if (id == R.id.menu_new_folder)
+            mainActivity.mainActivityHelper.mkdir(openMode, path, mainFragment);
+          else if (id == R.id.menu_new_file)
+            mainActivity.mainActivityHelper.mkfile(openMode, path, mainFragment);
+          else if (id == R.id.menu_new_cloud)
+            new CloudSheetFragment()
+                .show(mainActivity.getSupportFragmentManager(), CloudSheetFragment.TAG_FRAGMENT);
+
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java:1811]: Code-wise looks OK. Although I'd prefer original `switch` instead of if-else branches unless it's proven to have speed advantage.

Comment (VishnuSanal) [reply app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java:1811]: I was getting a warning with `switch` case: "Resource IDs will be non-final in Android Gradle Plugin version 8.0, avoid using them in switch case statements". Converting to `if else` was the suggested solution.

**Review by VishalNehra — APPROVED** [review]
