### PR TITLE
Use Completable instead of Flowable to refresh Drawer

### LINKED ISSUE #3478: `CalledFromWrongThreadException` on `Drawer#refreshDrawer` when deleting a bookmark
**crash when deleting a bookmark**

**To Reproduce**
1. Go to 'Menu'
2. choose any bookmark and Click 'Edit icon'
3. click 'DELETE'

**Formatted report**
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 12 - 31
* __Device:__ RMX3092CN
* __Model:__ RMX3092
* __Product:__ RMX3092
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
	at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14826)
	at io.reactivex.Flowable.subscribe(Flowable.java:14773)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10160)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1969)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1303)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at android.view.ViewExtImpl.hookRequestLayout(ViewExtImpl.java:509)
	at android.view.View.requestLayout(View.java:26058)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5541)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
	at com.google.android.material.internal.NavigationMenuPresenter$NavigationMenuAdapter.update(NavigationMenuPresenter.java:547)
	at com.google.android.material.internal.NavigationMenuPresenter.updateMenuView(NavigationMenuPresenter.java:128)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
	at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1063)
	at androidx.appcompat.view.menu.MenuBuilder.clear(MenuBuilder.java:609)
	at com.amaze.filemanager.ui.views.drawer.Drawer.refreshDrawer(Drawer.java:289)
	at com.amaze.filemanager.ui.activities.MainActivity.lambda$delete$28(MainActivity.java:2092)
	at com.amaze.filemanager.ui.activities.MainActivity.$r8$lambda$JVYr-HhdTlE0Boxbt7PNlgnho9M(Unknown Source:0)
	at com.amaze.filemanager.ui.activities.MainActivity$$ExternalSyntheticLambda18.accept(Unknown Source:4)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	... 13 more

```
</details>
<hr>

**Smartphone (please complete the following information):**
 - Device: [RMX3092CN]
 - OS: [Linux Android 12 - 31]
 - Rooted: [No]
 - Version: [3.8]

### PR DESCRIPTION
**Pull request by TranceLove**
## Description
Following suit from other parts of `MainActivity` to refresh `Drawer` after updating database.

Also refactored `MainActivity.addConnection()` to use `Completable` too to add entirely new SMB connection to drawer.

#### Issue tracker   
Fixes #3478

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 6 emulator
- OS: Android 12

1. Add a bookmark
2. Open drawer
3. Tap the pen icon next to the newly created bookmark
4. Edit bookmark dialog opened
5. Tap **Delete**
6. Bookmark is deleted without app crash

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java [hunk 1]
```diff
@@ -2066,42 +2074,47 @@ public void addConnection(
...
-      Flowable.fromCallable(
+      Completable.fromCallable(
               () -> {
                 utilsHandler.removeFromDatabase(
                     new OperationData(UtilsHandler.Operation.SMB, name, path));
                 return true;
               })
           .subscribeOn(Schedulers.io())
-          .subscribe(o -> drawer.refreshDrawer());
+          .observeOn(AndroidSchedulers.from(Looper.getMainLooper()))
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java:2089]: Won't `AndroidSchedulers.mainThread()` do the trick?

File: app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java [hunk 2]
```diff
@@ -2066,42 +2074,47 @@ public void addConnection(
...
-    Flowable.fromCallable(
+    Completable.fromCallable(
             () -> {
               utilsHandler.removeFromDatabase(
                   new OperationData(UtilsHandler.Operation.BOOKMARKS, title, path));
               return true;
             })
         .subscribeOn(Schedulers.io())
-        .subscribe(o -> drawer.refreshDrawer());
+        .observeOn(AndroidSchedulers.from(Looper.getMainLooper()))
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java:2104]: `AndroidSchedulers.mainThread()`

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]
