### PR TITLE
Fixes issue #2244 -> NPE on SwipeRefreshView while searching

### LINKED ISSUE #2244: NPE on SwipeRefreshView while searching
## Exception 
* __User Action:__ UI Error 
* __Request:__ Application crash 
* __Version:__ 3.5.3 
* __OS:__ Linux Android 10 - 29 
* __Device:__ gts4lwifi 
* __Model:__ SM-T830 
* __Product:__ gts4lwifixx 
* Crash log

``` 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.amaze.filemanager.ui.fragments.MainFragment.mSwipeRefreshLayout' on a null object reference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623) 
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775) 
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
 at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:8107)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.amaze.filemanager.ui.fragments.MainFragment.mSwipeRefreshLayout' on a null object reference
 at com.amaze.filemanager.ui.activities.MainActivity.onPreExecute(MainActivity.java:1849)
 at com.amaze.filemanager.asynchronous.asynctasks.SearchAsyncTask.onPreExecute(SearchAsyncTask.java:64)
 at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:708)
 at android.os.AsyncTask.execute(AsyncTask.java:655)
 at com.amaze.filemanager.ui.fragments.SearchWorkerFragment.onCreate(SearchWorkerFragment.java:88)
 at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
 at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
 at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
 at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
 at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
 at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
 at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
 at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
 at com.amaze.filemanager.ui.activities.superclasses.PreferenceActivity.onCreate(PreferenceActivity.java:58)
 at com.amaze.filemanager.ui.activities.superclasses.ThemedActivity.onCreate(ThemedActivity.java:55)
 at com.amaze.filemanager.ui.activities.MainActivity.onCreate(MainActivity.java:272)
 at android.app.Activity.performCreate(Activity.java:7957)
 at android.app.Activity.performCreate(Activity.java:7946)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
 ... 11 more
 ```

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2244 (Hopefully!)

#### Release  
Addresses release/3.6
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishnuSanal** [comment]
Should I log that?

File: app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java [hunk 1]
```diff
@@ -1857,7 +1857,7 @@ public void modify(String oldpath, String oldname, String newPath, String newnam
   @Override
   public void onPreExecute(String query) {
     final MainFragment mainFragment = getCurrentMainFragment();
-    Objects.requireNonNull(mainFragment);
+    if (mainFragment == null) return;
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java:1860]: I think before returning null, should show a toast saying 'Operation unsuccessful' or something similar.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]
