### PR TITLE
Service multithreading with ScheduledExecutorService instead of…

### LINKED ISSUE #1173: Crash on move
Moving ~>200 files from different folders app crashed with:

```gradle
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.amaze.filemanager, PID: 17313
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalStateException: This is not the first datapoint!
        at com.amaze.filemanager.asynchronous.services.AbstractProgressiveService.addFirstDatapoint(AbstractProgressiveService.java:169)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:216)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:186)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

Notification afterwards is stuck.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Added RepeatingRunnable and used for Waiting notification
* Used RepeatingRunnable for ServiceWatcherUtil.watch()
* Moved ServiceWatcherRepeatingRunnable to its own class in ServiceWatcherUtil
* Renamed ServiceWatcherInteractionInterface to ServiceStatusCallbacks
* Moved ServiceWatcherUtil into asynchronous.management
* Removed unused constructor for ProgressHandler 

Fixes #1173.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/asynchronous/AbstractRepeatingRunnable.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    public AbstractRepeatingRunnable(long initialDelay, long period, @NonNull TimeUnit unit, boolean startImmediately) {
+        if(!startImmediately) {
+            throw new UnsupportedOperationException("RepeatingRunnables are immediatly excecuted!");
+        }
+
+        ScheduledExecutorService threadExcecutor = Executors.newScheduledThreadPool(0);
+        handle = threadExcecutor.scheduleAtFixedRate(this, initialDelay, period, unit);
+    }
+
+    public abstract void run();
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/asynchronous/AbstractRepeatingRunnable.java]: It is not necessary to re-declare `public abstract void run()` here - you are implementing `Runnable`, and you expect `Runnable.run()` is implemented by subclasses of `AbstractRepeatingRunnable`.

File: app/src/main/java/com/amaze/filemanager/asynchronous/management/ServiceWatcherUtil.java [hunk 2]
```diff
@@ -0,0 +1,253 @@
...
+import com.amaze.filemanager.asynchronous.AbstractRepeatingRunnable;
+import com.amaze.filemanager.asynchronous.services.AbstractProgressiveService;
+import com.amaze.filemanager.ui.notifications.NotificationConstants;
+import com.amaze.filemanager.utils.ProgressHandler;
+
+import java.lang.ref.WeakReference;
+import java.util.concurrent.*;
+
+import static com.amaze.filemanager.asynchronous.management.ServiceWatcherUtil.ServiceStatusCallbacks.*;
+import static com.amaze.filemanager.asynchronous.management.ServiceWatcherUtil.ServiceStatusCallbacks.STATE_UNSET;
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/asynchronous/management/ServiceWatcherUtil.java]: Redundant import.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/asynchronous/management/ServiceWatcherUtil.java]: We should turn on lint for automated redundant imports checks... Will fix these ones.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/asynchronous/management/ServiceWatcherUtil.java]: Fixed. But, was there any end user perf effect?

**Comment by TranceLove** [comment]
Sorry for the late reply.

Tested with Oneplus 2 running Slim7 (7.1.2), using copy, encrypt/decrypt, extracting/compressing zip files, and also copy over SMB/SSH, seems to have no obvious problem with my daily usage.

However, will this changeset facilitate executing the above `Service`-based operations simultaneously? I tried a case of copying another file over SSH (Task 2) when I was still copying the first batch of files to the same SSH server (Task 1), Amaze crashed after Task 1 was done copying.

**Comment by EmmanuelMess** [comment]
> However, will this changeset facilitate executing the above `Service`-based operations simultaneously? I tried a case of copying another file over SSH (Task 2) when I was still copying the first batch of files to the same SSH server (Task 1), Amaze crashed after Task 1 was done copying.

It will take some time to check the feasibility and get the atomicity necesary for simultaneous operations: "too complicated, not now".

**Comment by VishalNehra** [comment]
@EmmanuelMess please explain if this is a refactor from your side or a bugfix. 
@TranceLove I see you faced a crash when switching to task 2 which was started when task 1 was being executed. Please confirm if you the issue is fixed for you.

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess please explain if this is a refactor from your side or a bugfix.

Both, I get frequent crashes form services, this seems to help. It is also a refactor to make the logic easier to understand and debug.

**Comment by EmmanuelMess** [comment]
@TranceLove I may have missunderstood, did you force simultaneous operations or did you simply start task two while task one was running (without changing the code)?

**Comment by TranceLove** [comment]
@EmmanuelMess as a little test, started Task 2 when Task 1 is still running.

**Comment by EmmanuelMess** [comment]
@TranceLove Ok, that *is* a bug, sorry.

**Comment by EmmanuelMess** [comment]
@TranceLove should be fixed now.

**Comment by TranceLove** [comment]
> @TranceLove should be fixed now.
> Fixes #1173.

Tested on Oneplus 2 running Slim7 (7.1.2) and LG Nexus 5x running AOSPExtended (9.0), to copy and move files across directories on the same device storage, worked. The copy processes starts one after another without crash.

Also tested on Oneplus 2 running Slim7 (7.1.2), to copy multiple folders over SCP. Copy processes also started one after another without crash. However the last copy process didn't end (progress at notification bar didn't go away).

Not sure if I should give a tick here... but other than this it should be good.

**Comment by EmmanuelMess** [comment]
@TranceLove 
> However the last copy process didn't end (progress at notification bar didn't go away).

Will try to fix that tomorrow.

**Comment by EmmanuelMess** [comment]
@TranceLove 

> However the last copy process didn't end (progress at notification bar didn't go away).

Are you sure this is not a bug already in main? 

One way it could be happening is that `setCanceled(true)` here:

https://github.com/TeamAmaze/AmazeFileManager/blob/ce20a4655448f4f72f223b32b11c2b3d00ee94b1/app/src/main/java/com/amaze/filemanager/asynchronous/services/AbstractProgressiveService.java#L246

Could be called before `progressHalted()` here:

https://github.com/TeamAmaze/AmazeFileManager/blob/ce20a4655448f4f72f223b32b11c2b3d00ee94b1/app/src/main/java/com/amaze/filemanager/asynchronous/management/ServiceWatcherUtil.java#L111

Causing an eternal "progress halted" notification.

**Comment by EmmanuelMess** [comment]
@bowiechen corrected typos.

**Comment by EmmanuelMess** [comment]
@TranceLove is this still ok? If so we can merge.
