### PR TITLE
Fixes issue #2115 -> Cant create a folder after cut/copy

### LINKED ISSUE #2115: Cant create a folder after cut/copy
Trying to copy to a new folder I'll usually go to the copy site and the create a new folder, but if I have files in the clipboard I cant.

### PR DESCRIPTION
**Pull request by VishnuSanal**
## PR Info

Fixes #2115

#### Release  
Addresses release/3.6
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Realme Narzo 20A
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Additional Info
@VishalNehra Please take a look

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 1]
```diff
@@ -365,6 +325,46 @@ public static Snackbar showThemedSnackbar(
...
+
+    actionButton.setText(actionTextId);
+    textView.setText(text);
+
+    actionButton.setOnClickListener(v -> actionCallback.run());
+    cancelButton.setOnClickListener(v -> cancelCallback.run());
+
+    snackBarLayout.addView(customSnackView, 0);
+
+    if (mainActivity.getAppTheme().equals(AppTheme.LIGHT)) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java:358]: A few themes missing here

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 2]
```diff
@@ -365,6 +325,46 @@ public static Snackbar showThemedSnackbar(
...
+      ((CardView) snackBarLayout.findViewById(R.id.snackBarCardView))
+          .setCardBackgroundColor(mainActivity.getResources().getColor(android.R.color.white));
+      textView.setTextColor(mainActivity.getResources().getColor(android.R.color.black));
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java:361]: This shouldn't be set manually, because some background colors need different text colors to be readable.

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java (hunk 1 above)
Comment (VishnuSanal) [reply app/src/main/java/com/amaze/filemanager/utils/Utils.java:358]: @EmmanuelMess This push contains the black and white one as @VishalNehra asked for checking how it looks...

**Comment by EmmanuelMess** [comment]
@VishalNehra @VishnuSanal too little contrast between paste view and background is a problem IMO. Maybe a paste view that has a background little darker for the light theme and a little lighter for the dark thremes?

**Review by EmmanuelMess — APPROVED** [review]

**Comment by VishalNehra** [comment]
Build test apk

File: app/src/main/res/layout/snackbar_view.xml [hunk 3]
```diff
@@ -0,0 +1,64 @@
+<?xml version="1.0" encoding="utf-8"?>
+<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
```
Comment (VishalNehra) [inline app/src/main/res/layout/snackbar_view.xml:2]: Cardview shouldn't be the root. Please enclose cardview within another ConstraintLayout. Give padding to this parent layout instead to the cardview.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]
