### PR TITLE
Proguard instruction to keep CompressorInputStream descendants' constructors taking InputStream as parameter

### LINKED ISSUE #2642: Crash on opening .tgz file
## Issue explanation (write below this line)

Tried to open .tgz file and got this crash message. App is up to date and already tried force stopping and clearing cache.

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 11 - 30
* __Device:__ sargo
* __Model:__ Pixel 3a
* __Product:__ sargo
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	... 1 more
Caused by: java.lang.NoSuchMethodException: org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init> [class java.io.InputStream]
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
	at com.amaze.filemanager.asynchronous.asynctasks.compress.AbstractCompressedTarArchiveHelperTask.<init>(AbstractCompressedTarArchiveHelperTask.kt:46)
	at com.amaze.filemanager.asynchronous.asynctasks.compress.GzipHelperTask.<init>(GzipHelperTask.kt:38)
	at com.amaze.filemanager.filesystem.compressed.showcontents.helpers.GzipDecompressor.changePath(GzipDecompressor.kt:37)
	at com.amaze.filemanager.filesystem.compressed.showcontents.helpers.GzipDecompressor.changePath(GzipDecompressor.kt:31)
	at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.changePath(CompressedExplorerFragment.java:435)
	at com.amaze.filemanager.ui.fragments.CompressedExplorerFragment.onActivityCreated(CompressedExplorerFragment.java:226)
	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2983)
	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:577)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	... 3 more

```
</details>
<hr>

### LINKED ISSUE #2647: Crash when extract .tar.gz file
**Describe the bug**
Crash when extract tar.gz file

An exmaple fie:
[gz.tar.gz](https://github.com/TeamAmaze/AmazeFileManager/files/6680325/gz.tar.gz)

**To Reproduce**
1. Click .tar.gz file
2. Click extract button
3. Amaze crash

**Expected behavior**
File is extracted.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi]
 - OS: [Lineage OS 16.0]
 - Rooted: [No]
 - Version: [last commit build]

**Additional context**
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodException: <init> [class java.io.InputStream]
	at java.lang.Class.getConstructor0(Class.java:2327)
	at java.lang.Class.getDeclaredConstructor(Class.java:2166)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.AbstractCompressedTarArchiveExtractor.<init>(AbstractCompressedTarArchiveExtractor.kt:43)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.GzipExtractor.<init>(GzipExtractor.kt:34)
	at com.amaze.filemanager.filesystem.compressed.CompressedHelper.getExtractorInstance(CompressedHelper.java:91)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:274)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:227)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

```

### LINKED ISSUE #2655: Crash on extract RAR on Android 6.0
## Issue explanation (write below this line)
Problem is at `Archive`, using `Stream` which is available from API 24:

https://github.com/junrar/junrar/blob/bac58479ad4731a31363e8626f167e9a2d84daac/src/main/java/com/github/junrar/Archive.java#L265-L268
```java
    public boolean isPasswordProtected() throws RarException {
        if (isEncrypted()) return true;
        return getFileHeaders().stream().anyMatch(FileHeader::isEncrypted);
    }
```

## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.6.1
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 6.0 - 23
* __Device:__ generic_x86
* __Model:__ Android SDK built for x86
* __Product:__ sdk_google_phone_x86
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
	at com.github.junrar.Archive.isPasswordProtected(Archive.java:267)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.helpers.RarExtractor.extractWithFilter(RarExtractor.kt:71)
	at com.amaze.filemanager.filesystem.compressed.extractcontents.Extractor.extractEverything(Extractor.java:82)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:318)
	at com.amaze.filemanager.asynchronous.services.ExtractService$DoWork.doInBackground(ExtractService.java:227)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by TranceLove**
Call this black magic, since it's not possible to even run an Espresso test against classes processed with Proguard.

Anyone have a better idea to test logic after Proguard processing, please let us know.

Additionally, fixed a regression in RarExtractor that would cause Amaze to crash when extracting RAR on Android 6.0 or lower - see #2655.

#### Issue tracker   
Fixes #2642, fixes #2647, fixes #2655

#### Manual tests
- [x] Done  

- Device: Pixel 2 emulator
- OS: Android 6.0, Android 11.

Create a production build (which will include proguard) then test extracting different archives as usual.

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/filesystem/compressed/RarArchiveExt.kt [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+/**
+ * Extension function to patch [Archive.isPasswordProtected] which uses API that is not available
+ * for Android 6.0 or lower.
+ *
+ * @see [Archive.isPasswordProtected]
+ * @see [java.util.stream.Stream]
+ * @return if archive is password protected
+ */
+fun Archive.isPasswordProtectedCompat(): Boolean {
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/compressed/RarArchiveExt.kt:35]: There's a generic extension kotlin file already. I don't think it's required to create another Rar specific kotlin file.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/amaze/filemanager/filesystem/compressed/RarArchiveExt.kt (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/filesystem/compressed/RarArchiveExt.kt:35]: Against, please keep the functions in the package they belong to, aka this in compressed.

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/filesystem/compressed/RarArchiveExt.kt:35]: Ok even then a separate file for rar extension function is definitely not required. It's just too much segregation.

**Comment by EmmanuelMess** [comment]
I am getting instant crash on install.

**Comment by VishalNehra** [comment]
Build test apk

**Review by EmmanuelMess — APPROVED** [review]

**Comment by EmmanuelMess** [comment]
Tested on AVD API 31

**Review by VishalNehra — APPROVED** [review]
