### PR TITLE
Fix columns for grid layout for MainFragment

### LINKED ISSUE #3154: NPE when trying to show copy/paste snackbar and mainfragment is not attached
## Exception
* App Name: Amaze File Manager
* Package: com.amaze.filemanager
* Version: 3.6.7
* User Action: UI Error
* Request: Application crash
* OS: Linux Android 7.0 - 24
* Device: GIONEE_SWW1609
* Model: GIONEE A1
* Product: A1
<details><summary><b>Crash log </b></summary><p>

```

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
 at com.amaze.filemanager.filesystem.PasteHelper$2.lambda$onSuccess$0(PasteHelper.java:162)
 at com.amaze.filemanager.filesystem.PasteHelper$2.lambda$onSuccess$0$PasteHelper$2(PasteHelper.java)
 at com.amaze.filemanager.filesystem.-$$Lambda$PasteHelper$2$WCIV1v6PgmNC7uG8zXvW9OLjAmQ.run(lambda)
 at com.amaze.filemanager.utils.Utils.lambda$showCutCopySnackBar$1(Utils.java:359)
 at com.amaze.filemanager.utils.-$$Lambda$Utils$4idEvFLOs3eF7-x6YKX_WvNl_IQ.onClick(lambda)
 at android.view.View.performClick(View.java:5682)
 at android.view.View$PerformClick.run(View.java:22669)
 at android.os.Handler.handleCallback(Handler.java:836)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loop(Looper.java:203)
 at android.app.ActivityThread.main(ActivityThread.java:6276)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```
</details>
<hr>

Reporter: None

### LINKED ISSUE #3249: Divide by zero on `MainFragment#onGlobalLayout`
## Exception
* App Name: Amaze
* Package: com.amaze.filemanager
* Version: 3.6.7
* User Action: UI Error
* Request: Application crash
* OS: Linux Android 10 - 29
* Device: LAS
* Model: LEAP-S1
* Product: HP4035-Mecool
<details><summary><b>Crash log </b></summary><p>

```

java.lang.ArithmeticException: divide by zero
 at com.amaze.filemanager.ui.fragments.MainFragment.onGlobalLayout(MainFragment.java:1642)
 at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2625)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1718)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7595)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
 at android.view.Choreographer.doCallbacks(Choreographer.java:790)
 at android.view.Choreographer.doFrame(Choreographer.java:725)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

</details>
<hr>

Reporter: Magnolius7

### PR DESCRIPTION
**Pull request by EmmanuelMess**
## Description

This PR reworks how defaults are handled for grid columns preference and fixes a divide by zero crash. 

#### Issue tracker   

Fixes #3249

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishalNehra — APPROVED** [review]

File: app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt [hunk 1]
```diff
@@ -141,15 +143,9 @@ class MainFragmentViewModel : ViewModel() {
...
-            sharedPreferences.getString(
-                PreferencesConstants
-                    .PREFERENCE_GRID_COLUMNS,
-                "-1"
-            )?.toInt()?.run {
-                columns = this
-            }
-        }
+        val columnPreference = sharedPreferences.getString(PREFERENCE_GRID_COLUMNS, PREFERENCE_GRID_COLUMNS_DEFAULT)
+        Objects.requireNonNull(columnPreference)
```
Comment (VishnuSanal) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt:147]: ` Objects#requireNonNull` would throw an NPE if `columnPreference` is `null`. Did you mean `if(columnPreference != null)`?

**Review by VishnuSanal — COMMENTED** [review]
@EmmanuelMess Please see the comments - a simple clarification.

File: app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt:147]: It will never be null.
