### PR TITLE
Check working directory and change to root before listing files

### LINKED ISSUE #3476: [root] treats /data/data as /
**Describe the bug**
Navigating to `/ Root` brings to `/data/data`

**To Reproduce**
1. Tap on `/ Root`
2. See `/` on top but the real contents is of `/data/data`

**Expected behavior**
Show the contents of `/`

**Smartphone (please complete the following information):**
 - Device: phhgsi_arm64_ab / AGM H3
 - OS: Android 12 / lineage_arm64_bvS
 - Rooted: [e.g. No]
 - Version: 3.8

**Additional context**
AFM shows /data/data/* contents and **a user cannot navigate** to ..
The possible reason may be the following: the Phh's SU brings to /data/data instead of `/` as other `su` implementations:
```
phhgsi_arm64_ab:/ $ su
:/data/data #
```

### PR DESCRIPTION
**Pull request by TranceLove**
## Description
Also fixes line parsing of filenames having colons as I work on, listing files under `/dev`.

#### Issue tracker   
Fixes #3476 

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  
#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt [hunk 1]
```diff
@@ -124,6 +124,12 @@ object ListFilesCommand : IRootCommand() {
                         PreferencesConstants.PREFERENCE_ROOT_LEGACY_LISTING,
                         false
                     )
+            // #3476: Check current working dir, change back to / before proceeding
+            runShellCommand("pwd").run {
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt:128]: How did you test this? There was a reason `/` was replaced in line 115. A better approach will be to just not replace `/` in 115 but needs testing with different su binaries.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Comment by ildar** [comment]
on testing: note that the GSI ROM is indeed installable on numerous of
smartphones.
Details here: https://github.com/phhusson/treble_experimentations/wiki

File: app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt (hunk 1 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt:128]: The code combination so far it works on both Magisk's `busybox` by 0smosis and `toybox`.

> Also, here you're always cd to root / regardless of user navigate to any directory. Won't this restrict user to navigation to any directory other than the root?

Amaze always run `ls` or `stat` with full paths, so there will not be problem of always start from `/`.

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt:128]: I don't like this approach. Basically every time we list we're going to run two commands, doesn't seem right, even if it does the job, this is adding a overhead.
What happens if we just remove line 115? Is there any issue?

Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/filesystem/root/ListFilesCommand.kt:125]: OK, fair enough. That was a trick to prevent sending a `//` to root commands. Should have used an easier way.

And on the overhead of `pwd` and `cd /`, unless we are sure the root shell is used throughout the whole lifecycle of the app, we can't be sure if the second time root shell brings up its `pwd` is staying the last session's ones.

**Comment by ildar** [comment]
1st, it's usually safe to have `//` instead of `/` for root
2. I'll try this PR when it's built for CI.

**Comment by ildar** [comment]
oops. Looks like CI doesn't export built apk's. Why? It's free!
Anyway, if you want I can test on my ROM.
Thanks for your work.

**Comment by VishnuSanal** [comment]
Build test APK

**Comment by ildar** [comment]
I don't have a good infrastructure, sorry

**Comment by VishnuSanal** [comment]
@ildar Um... That's the command to trigger the CI to build the test APK!

**Comment by ildar** [comment]
Ah! right. Yet failed, i.e. skipped.

**Comment by ildar** [comment]
allright! got it! and it works!
thanks a lot.

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
@TranceLove  can you please rebase this branch and fix conflict so that i can merge

**Comment by ildar** [comment]
## Issue explanation (write below this line)
Thank you guys. The app now mostly works but in one folder it crashed.
Other folders seem to work fine.

## Exception
* __App Name:__ Amaze
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.4
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux Android 13 - 33
* __Device:__ phhgsi_arm64_ab
* __Model:__ Phh-Treble vanilla
* __Product:__ treble_arm64_bvS
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: An error occurred while executing
doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:415)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
at java.util.concurrent.FutureTask.run(FutureTask.java:269)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NumberFormatException: For input string: "1668595893 |
SkillRestorePrefs:880807561:tr"
at java.lang.Long.parseLong(Long.java:736)
at java.lang.Long.parseLong(Long.java:861)
at
com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:945)
at
com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:228)
at
com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60)
at
com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDefault(LoadFilesListTask.java:705)
at
com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:187)
at
com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
... 3 more

```
</details>
<hr>

**Comment by TranceLove** [comment]
> ## Issue explanation (write below this line) Thank you guys. The app now mostly works but in one folder it crashed. Other folders seem to work fine. ## Exception * __App Name:__ Amaze * __Package:__ com.amaze.filemanager * __Version:__ 3.8.4 * __User Action:__ UI Error * __Request:__ Application crash * __OS:__ Linux Android 13 - 33 * __Device:__ phhgsi_arm64_ab * __Model:__ Phh-Treble vanilla * __Product:__ treble_arm64_bvS <details><summary><b>Crash log </b></summary><p> ``` java.lang.RuntimeException: An error occurred while executing doInBackground() at android.os.AsyncTask$4.done(AsyncTask.java:415) at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381) at java.util.concurrent.FutureTask.setException(FutureTask.java:250) at java.util.concurrent.FutureTask.run(FutureTask.java:269) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at java.lang.Thread.run(Thread.java:1012) Caused by: java.lang.NumberFormatException: For input string: "1668595893 | SkillRestorePrefs:880807561:tr" at java.lang.Long.parseLong(Long.java:736) at java.lang.Long.parseLong(Long.java:861) at com.amaze.filemanager.filesystem.files.FileUtils.parseName(FileUtils.java:945) at com.amaze.filemanager.filesystem.root.ListFilesCommand.parseStringForHybridFile(ListFilesCommand.kt:228) at com.amaze.filemanager.filesystem.root.ListFilesCommand.listFiles(ListFilesCommand.kt:60) at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.listDefault(LoadFilesListTask.java:705) at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:187) at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:85) at android.os.AsyncTask$3.call(AsyncTask.java:394) at java.util.concurrent.FutureTask.run(FutureTask.java:264) ... 3 more ``` </details> <hr>

Best if you can provide us with the result of `ls -l` and `stat -c '%A %h %G %U %B %Y %N'` at the directory causing the crash above.

**Comment by ildar** [comment]
<details><summary>yep</summary>
$ adb shell
phhgsi_arm64_ab:/ $ su
:/data/data # cd com.duolingo/shared_prefs/                                    
:/data/data/com.duolingo/shared_prefs # ls -al
total 892
drwxrwx--x  2 u0_a153 u0_a153 12288 2022-11-23 11:07 .
drwx------ 12 u0_a153 u0_a153  4096 2022-11-23 11:54 ..
-rw-rw----  1 u0_a153 u0_a153  2763 2022-11-04 22:54 AchievementPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   217 2022-11-22 11:24 AdsSettings.xml
-rw-rw----  1 u0_a153 u0_a153   281 2022-07-21 08:32 ContactsStatePrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   109 2022-11-18 20:30 CountryLocalizationPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   110 2022-06-30 10:50 DEBUG_PREF.xml
-rw-rw----  1 u0_a153 u0_a153   625 2022-11-22 11:37 DailyQuestPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   222 2022-11-23 11:07 DeviceIdsPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   445 2022-11-16 22:27 Duo.xml
-rw-rw----  1 u0_a153 u0_a153   490 2022-11-22 21:03 EarlyBirdPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153  3422 2022-11-21 11:27 ExperimentsAttemptedTreatmentsPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   267 2022-06-30 10:39 FBAdPrefs.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-06-30 10:39 FamilyPlanInviteTokenPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   239 2022-08-26 13:14 FirebaseAppHeartBeat.xml
-rw-rw----  1 u0_a153 u0_a153  1827 2022-11-23 10:15 FirebaseHeartBeatW0RFRkFVTFRd+MTo0NTAyOTg2ODYwNjU6YW5kcm9pZDplMjdlOTNlYWJmMGVkMjM0.xml
-rw-rw----  1 u0_a153 u0_a153   635 2022-11-20 15:34 FriendsQuestPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   200 2022-11-20 23:20 GlobalPracticePrefs.xml
-rw-rw----  1 u0_a153 u0_a153   589 2022-11-20 11:29 GoalsPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   122 2022-06-30 10:39 HapticFeedbackPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   136 2022-11-22 11:37 HardModePrefs.xml
-rw-rw----  1 u0_a153 u0_a153   137 2022-06-30 19:31 HasShownSpeakTooltip.xml
-rw-rw----  1 u0_a153 u0_a153   861 2022-11-22 11:37 HealthPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   138 2022-07-04 10:36 HintUtils.xml
-rw-rw----  1 u0_a153 u0_a153   127 2022-11-06 11:53 InputPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   192 2022-11-22 11:37 ItemOfferLastUpdatedCounter.xml
-rw-rw----  1 u0_a153 u0_a153 14522 2022-11-22 11:38 Leaderboards.xml
-rw-rw----  1 u0_a153 u0_a153   289 2022-09-04 19:03 LeagueRepairOfferPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   190 2022-11-21 11:25 LearnerSpeechStorePrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   163 2022-06-30 10:39 LocalePrefs.xml
-rw-rw----  1 u0_a153 u0_a153   125 2022-11-23 11:07 OkCookieJar.xml
-rw-rw----  1 u0_a153 u0_a153   126 2022-09-01 21:40 OnboardingCompletion.xml
-rw-rw----  1 u0_a153 u0_a153   341 2022-11-22 22:01 OnboardingState:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   120 2022-11-17 19:38 PathPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   846 2022-11-21 11:27 PerformanceTestOutPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   153 2022-11-21 10:27 PermissionUtils.xml
-rw-rw----  1 u0_a153 u0_a153  1983 2022-11-22 11:37 PlusPrefs:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   177 2022-06-30 10:40 ProfileCompletionPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   283 2022-11-22 11:37 ProgressManagerPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   214 2022-11-21 11:27 ProgressQuiz.xml
-rw-rw----  1 u0_a153 u0_a153   694 2022-11-22 22:01 ReferralPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   120 2022-11-17 19:56 ResurrectedOnboardingState:880807561.xml
-rw-rw----  1 u0_a153 u0_a153   159 2022-11-20 23:46 SkillActivityPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   205 2022-11-16 16:52 SkillPracticePrefs.xml
-rw-rw----  1 u0_a153 u0_a153  1385 2022-11-16 16:51 SkillRestorePrefs:880807561:tr\ <-\ en.xml
-rw-rw----  1 u0_a153 u0_a153   817 2022-06-30 10:39 StoriesPrefs.xml
-rw-rw----  1 u0_a153 u0_a153   698 2022-11-18 20:36 StreakPrefs.xml
-rw-rw----  1 u0_a153 u0_a153  1093 2022-11-16 22:27 TrackingSamplingRates.xml
-rw-rw----  1 u0_a153 u0_a153   127 2022-11-22 11:24 WebViewChromiumPrefs.xml
-rw-rw----  1 u0_a153 u0_a153  3713 2022-11-19 10:47 ab_prefs.xml
-rw-rw----  1 u0_a153 u0_a153   122 2022-06-30 10:38 adjust_preferences.xml
-rw-rw----  1 u0_a153 u0_a153 42660 2022-11-22 22:01 admob.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-06-30 19:30 android-grade:configuration.xml
-rw-rw----  1 u0_a153 u0_a153   302 2022-11-23 11:07 app_rating.xml
-rw-rw----  1 u0_a153 u0_a153   127 2022-06-30 10:39 com.duolingo.excess.prefs.v1.xml
-rw-rw----  1 u0_a153 u0_a153   145 2022-06-30 10:39 com.duolingo.tracking_preferences.xml
-rw-rw----  1 u0_a153 u0_a153   240 2022-06-30 10:39 com.duolingo.v2.xml
-rw-rw----  1 u0_a153 u0_a153   415 2022-11-21 11:41 com.duolingo_preferences.xml
-rw-rw----  1 u0_a153 u0_a153   306 2022-06-30 10:40 com.facebook.ads.FEATURE_CONFIG.xml
-rw-rw----  1 u0_a153 u0_a153  1538 2022-11-21 21:12 com.facebook.internal.MODEL_STORE.xml
-rw-rw----  1 u0_a153 u0_a153  3692 2022-11-22 09:00 com.facebook.internal.preferences.APP_GATEKEEPERS.xml
-rw-rw----  1 u0_a153 u0_a153  1643 2022-11-22 20:59 com.facebook.internal.preferences.APP_SETTINGS.xml
-rw-rw----  1 u0_a153 u0_a153   138 2022-06-30 10:38 com.facebook.sdk.USER_SETTINGS.xml
-rw-rw----  1 u0_a153 u0_a153   160 2022-06-30 10:38 com.facebook.sdk.appEventPreferences.xml
-rw-rw----  1 u0_a153 u0_a153   388 2022-11-16 22:27 com.google.android.gms.appid.xml
-rw-rw----  1 u0_a153 u0_a153   724 2022-11-22 22:13 com.google.android.gms.measurement.prefs.xml
-rw-rw----  1 u0_a153 u0_a153   333 2022-11-16 22:27 com.google.firebase.crashlytics.xml
-rw-rw----  1 u0_a153 u0_a153   183 2022-06-30 10:38 com.google.firebase.messaging.xml
-rw-rw----  1 u0_a153 u0_a153   261 2022-11-22 20:59 com.vungle.sdk.xml
-rw-rw----  1 u0_a153 u0_a153   137 2022-08-15 18:32 crash_handler_prefs.xml
-rw-rw----  1 u0_a153 u0_a153   140 2022-06-30 10:39 dark_mode_home_message_prefs.xml
-rw-rw----  1 u0_a153 u0_a153  1198 2022-11-16 22:27 debug_flags.xml
-rw-rw----  1 u0_a153 u0_a153   201 2022-07-01 08:34 final_level_skill_state.xml
-rw-rw----  1 u0_a153 u0_a153   504 2022-11-23 10:15 frc_1:450298686065:android:e27e93eabf0ed234_firebase_settings.xml
-rw-rw----  1 u0_a153 u0_a153   128 2022-11-22 11:24 google_auto_usage.xml
-rw-rw----  1 u0_a153 u0_a153   128 2022-11-22 21:39 google_conversion.xml
-rw-rw----  1 u0_a153 u0_a153   126 2022-06-30 10:38 google_nonrepeatable_conversion.xml
-rw-rw----  1 u0_a153 u0_a153  1570 2022-11-22 11:38 lesson_coach_counter.xml
-rw-rw----  1 u0_a153 u0_a153   117 2022-07-02 10:33 match_challenge.xml
-rw-rw----  1 u0_a153 u0_a153   137 2022-11-20 00:03 news_prefs.xml
-rw-rw----  1 u0_a153 u0_a153   125 2022-11-21 11:34 next_lesson_hook_prefs.xml
-rw-rw----  1 u0_a153 u0_a153   859 2022-08-31 19:16 onboarding_parameters.xml
-rw-rw----  1 u0_a153 u0_a153   207 2022-11-22 10:31 pref_name_fcm.xml
-rw-rw----  1 u0_a153 u0_a153   300 2022-11-22 22:01 prefs_performance_mode_4.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-11-07 06:36 site_availability.xml
-rw-rw----  1 u0_a153 u0_a153   195 2022-11-22 21:03 store_counter.xml
-rw-rw----  1 u0_a153 u0_a153   149 2022-06-30 10:40 unityads-installinfo.xml
-rw-rw----  1 u0_a153 u0_a153  2236 2022-11-22 11:37 user_880807561_en_tr_learning_summary.xml
-rw-rw----  1 u0_a153 u0_a153   555 2022-11-22 20:59 user_880807561_feed_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-11-16 22:27 user_880807561_goals_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153   455 2022-11-20 23:46 user_880807561_leaderboards_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153   239 2022-11-21 10:26 user_880807561_match_madness.xml
-rw-rw----  1 u0_a153 u0_a153   296 2022-11-16 22:27 user_880807561_mistakes_inbox_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-11-20 23:46 user_880807561_path_last_chest.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-11-16 22:27 user_880807561_profile_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153   605 2022-11-22 21:03 user_880807561_shop_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-11-16 22:27 user_880807561_stories_tab_unified_red_dots_state.xml
-rw-rw----  1 u0_a153 u0_a153   131 2022-11-20 00:02 user_880807561_streak_prefs.xml
-rw-rw----  1 u0_a153 u0_a153   431 2022-11-17 19:57 user_880807561_streak_society.xml
-rw-rw----  1 u0_a153 u0_a153   121 2022-11-22 12:19 web_view_cache_clearing.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-07-02 10:37 zendesk_additional_sdk.xml
-rw-rw----  1 u0_a153 u0_a153   178 2022-07-02 10:37 zendesk_identity.xml
-rw-rw----  1 u0_a153 u0_a153   148 2022-07-02 10:37 zendesk_sdk.xml
-rw-rw----  1 u0_a153 u0_a153    65 2022-07-02 10:37 zendesk_settings.xml
:/data/data/com.duolingo/shared_prefs # stat -c '%A %h %G %U %B %Y %N' 
stat: Needs 1 argument (see "stat --help")
1|:/data/data/com.duolingo/shared_prefs # stat -c '%A %h %G %U %B %Y %N' .
drwxrwx--x 2 u0_a153 u0_a153 512 1669180037 .
:/data/data/com.duolingo/shared_prefs # 
</details>

**Comment by TranceLove** [comment]
For `stat` command please try posting the output of `stat -c '%A %h %G %U %B %Y %N' /data/data/*`.

But for the output above, this line looks interesting 🤔
```
-rw-rw----  1 u0_a153 u0_a153  1385 2022-11-16 16:51 SkillRestorePrefs:880807561:tr\ <-\ en.xml
```

**Comment by ildar** [comment]
On Wed, Nov 23, 2022 at 12:34 PM Raymond Lai wrote:

> For stat command please try posting the output of stat -c '%A %h %G %U %B
> %Y %N' /data/data/*.
>
`/data/data` is shown without a problem.
Crash happens opening `/data/data/com.duolingo/shared_prefs`
