### PR TITLE
Capture SecurityException when reading USB serial number

### LINKED ISSUE #2148: SecurityException on usb
## Exception
 * __User Action:__ UI Error
 * __Request:__ Application crash
 * __Version:__ 3.5.2
 * __OS:__ Linux samsung/gts4llteusc/gts4llteusc:10/QP1A.190711.020/T837R4TYU4CTH5:user/release-keys 10 - 29
 * __Device:__ gts4llteusc
 * __Model:__ SM-T837R4
 * __Product:__ gts4llteusc Crash log

```
java.lang.RuntimeException: Unable to resume activity {com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.SecurityException: User has not given 10281/com.amaze.filemanager permission to access device /dev/bus/usb/001/008
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4626)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4659)
 at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:237)
 at android.app.ActivityThread.main(ActivityThread.java:8107)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
 Caused by: java.lang.SecurityException: User has not given 10281/com.amaze.filemanager permission to access device /dev/bus/usb/001/008
 at android.os.Parcel.createException(Parcel.java:2088)
 at android.os.Parcel.readException(Parcel.java:2056)
 at android.os.Parcel.readException(Parcel.java:2004)
 at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
 at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:143) at com.amaze.filemanager.utils.OTGUtil.getMassStorageDevicesConnected(OTGUtil.java:168) at com.amaze.filemanager.ui.activities.MainActivity.updateUsbInformation(MainActivity.java:1203) at com.amaze.filemanager.ui.activities.MainActivity.onResume(MainActivity.java:1195) at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454) at android.app.Activity.performResume(Activity.java:8105) at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4616) ... 11 more Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.usb.UsbUserSettingsManager.checkPermission(UsbUserSettingsManager.java:219) at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:96) at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:84) at android.os.Binder.execTransactInternal(Binder.java:1056) at android.os.Binder.execTransact(Binder.java:1029) ```

### PR DESCRIPTION
**Pull request by TranceLove**
Capture SecurityException that may throw on devices running Android 10 or above.

References:
https://github.com/altera2015/usbserial/pull/21
https://developer.android.com/reference/android/hardware/usb/UsbDevice#getSerialNumber()

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2148

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishalNehra — APPROVED** [review]

File: app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java [hunk 1]
```diff
@@ -47,7 +47,9 @@
 import androidx.documentfile.provider.DocumentFile;
 
 /** Created by Vishal on 27-04-2017. */
-public class OTGUtil {
+public abstract class OTGUtil {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java:50]: Adding abstract makes no sense, it has no abstract methods.

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java (hunk 1 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java]: Was habit to prevent others from instantiating utility classes... anyway.

**Comment by VishalNehra** [comment]
Build test apk

File: app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/OTGUtil.java]: A private constructor would be a solution I would approve.

**Review by EmmanuelMess — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Build test apk
