### PR TITLE
Fix openmode when non-numeric path passed into LoadFilesListTask

### LINKED ISSUE #2225: ".log " file causes crash
## Exception
* User Action: UI Error
* Request: Application crash
* Version: 3.5.3
* OS: Linux Android 11 - 30
* Device: I1928
* Model: I1927
* Product: I1927
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$4.done(AsyncTask.java:415)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NumberFormatException: For input string: "/storage/emulated/0/.log"
 at java.lang.Integer.parseInt(Integer.java:604)
 at java.lang.Integer.parseInt(Integer.java:650)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:156)
 at com.amaze.filemanager.asynchronous.asynctasks.LoadFilesListTask.doInBackground(LoadFilesListTask.java:67)
 at android.os.AsyncTask$3.call(AsyncTask.java:394)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 ... 3 more

</details>
<hr>

Raised by: EmmanuelMess
Reporter: rkumarhyd22

### PR DESCRIPTION
**Pull request by TranceLove**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2225

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Fairphone 3 running LineageOS 16.0 (9.0), Oneplus 2 running /e/OS 0.13 (10)

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Additional Info
For some unknown reasons sometimes folder would show up at Documents list, i.e. identified as Document in MediaStore. Amaze would crash when attempt to tap into such folder while in Documents list, i.e. openmode is set to CUSTOM.

Workaround this problem by parsing the path before the switch(openmode) cases, and change openmode when path is not numeric.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java [hunk 1]
```diff
@@ -111,6 +111,13 @@ public LoadFilesListTask(
 
     nullCheckOrInterrupt(mainFragment, this).folder_count = 0;
     nullCheckOrInterrupt(mainFragment, this).file_count = 0;
+    int numericPath = -1;
+    try {
+      numericPath = Integer.parseInt(path);
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java:116]: I don' think we should do so much of recomputation just to fix a small issue. You're almost always calculating openmode here again on each load list task, moreover this'll fill logs with warn messages.
I think this try/catch should be moved to switch case `CUSTOM` and maybe you can try to load list again if possible otherwise show a way to denote a failed operation (unsupported operation toast or something similar).

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by EmmanuelMess — APPROVED** [review]

**Comment by VishalNehra** [comment]
Very smart changeset here @TranceLove

**Review by VishalNehra — APPROVED** [review]
