### PR TITLE
Display error messages as Toast and finish TextEditorActivity on load file problems

### LINKED ISSUE #1033: Errors in TextEditor should be dialog or toast
Errors in TextEditor should be dialog saying what failed and how to fix or toast and TextEditor should close in the latter.

### PR DESCRIPTION
**Pull request by TranceLove**
An effort to fix #1033.

It's probably a bad idea to call `finish()` to end TextEditorActivity, so feel free to put forward other better ideas.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java [hunk 1]
```diff
@@ -285,7 +285,8 @@ private void saveFile(final String editTextString) {
      * on a worker thread
      */
     private void load() {
-        mInput.setHint(R.string.loading);
+        Toast.makeText(getApplicationContext(), R.string.loading, Toast.LENGTH_SHORT).show();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java]: I think this should be a snackbar. For error we are not using snackbars because the activity is destroyed (and undissmissable dialogs are undissmissable).

File: app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java [hunk 2]
```diff
@@ -296,19 +297,22 @@ private void load() {
                     try {
                         mInput.setText(data.fileContents);
                         if (data.fileContents.isEmpty()) {
-                            mInput.setHint(R.string.file_empty);
+                            Toast.makeText(getApplicationContext(), R.string.file_empty, Toast.LENGTH_SHORT).show();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/activities/TextEditorActivity.java]: Revert to hint, "file is empty" is not a instantaneous error, it is a state the file is in, we are alerting the user via an always visible hint.

**Comment by TranceLove** [comment]
Merging.

Sorry for tapping the wrong button... the [build failure](https://travis-ci.org/TeamAmaze/AmazeFileManager/builds/351071510) was caused by a dependency resolve failure on Travis, not related to code itself.

> `Could not GET 'https://dl.google.com/dl/android/maven2/com/android/support/multidex/1.0.2/multidex-1.0.2.pom'. Received status code 502 from server: Bad Gateway`
