### PR TITLE
Fixes #3961

### LINKED ISSUE #3961: `CoderMalfunctionError` on `CharsetEncoder#encode`
## Exception
* App Name: Amaze File Manager
* Package: com.amaze.filemanager
* Version: 3.8.5
* User Action: UI Error
* Request: Application crash
* OS: Linux OnePlus/OnePlus8TTMO/OnePlus8TTMO:13/RKQ1.211119.001/R.202208261040:user/release-keys 13 - 33
* Device: OnePlus8TTMO
* Model: KB2007
* Product: OnePlus8TTMO
<details><summary><b>Crash log </b></summary><p>

```
java.nio.charset.CoderMalfunctionError: java.lang.IllegalArgumentException: Bad position 47/46
 at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:624)
 at org.apache.mina.core.buffer.AbstractIoBuffer.putString(AbstractIoBuffer.java:1811)
 at org.apache.ftpserver.listener.nio.FtpResponseEncoder.encode(FtpResponseEncoder.java:49)
 at org.apache.mina.filter.codec.ProtocolCodecFilter.filterWrite(ProtocolCodecFilter.java:299)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:629)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1500(DefaultIoFilterChain.java:48)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterWrite(DefaultIoFilterChain.java:957)
 at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:84)
 at org.apache.mina.filter.logging.MdcInjectionFilter.filter(MdcInjectionFilter.java:135)
 at org.apache.mina.filter.util.CommonEventFilter.filterWrite(CommonEventFilter.java:80)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:629)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1500(DefaultIoFilterChain.java:48)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterWrite(DefaultIoFilterChain.java:957)
 at org.apache.mina.core.filterchain.IoFilterAdapter.filterWrite(IoFilterAdapter.java:123)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:629)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1500(DefaultIoFilterChain.java:48)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.filterWrite(DefaultIoFilterChain.java:957)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.filterWrite(DefaultIoFilterChain.java:881)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.callPreviousFilterWrite(DefaultIoFilterChain.java:629)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireFilterWrite(DefaultIoFilterChain.java:622)
 at org.apache.mina.core.session.AbstractIoSession.write(AbstractIoSession.java:574)
 at org.apache.mina.core.session.AbstractIoSession.write(AbstractIoSession.java:519)
 at org.apache.ftpserver.impl.FtpIoSession.write(FtpIoSession.java:530)
 at org.apache.ftpserver.command.impl.PASV.execute(PASV.java:108)
 at org.apache.ftpserver.impl.DefaultFtpHandler.messageReceived(DefaultFtpHandler.java:211)
 at org.apache.ftpserver.listener.nio.FtpHandlerAdapter.messageReceived(FtpHandlerAdapter.java:62)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:858)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:947)
 at org.apache.ftpserver.listener.nio.FtpLoggingFilter.messageReceived(FtpLoggingFilter.java:85)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
 at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
```

Reporter: AiYuriW

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   

Fixes #3961

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [ ] `./gradlew assembledebug`
- [ ] `./gradlew spotlessCheck`

### CODE REVIEW

File: commons_compress_7z/src/main/java/com/amaze/filemanager/filesystem/compressed/sevenz/SevenZFile.java [hunk 1]
```diff
@@ -51,6 +52,7 @@
 import org.apache.commons.compress.utils.ByteUtils;
 import org.apache.commons.compress.utils.CRC32VerifyingInputStream;
 import org.apache.commons.compress.utils.InputStreamStatistics;
+import org.jetbrains.annotations.Nullable;
```
Comment (TranceLove) [inline commons_compress_7z/src/main/java/com/amaze/filemanager/filesystem/compressed/sevenz/SevenZFile.java:55]: Prefer not using `@Nullable` that is not from official Android SDK. Better pull it off at all.

File: commons_compress_7z/src/main/java/com/amaze/filemanager/filesystem/compressed/sevenz/SevenZFile.java [hunk 2]
```diff
@@ -2117,17 +2119,27 @@ public String getDefaultName() {
     return lastSegment + "~";
   }
 
+  @Nullable
```
Comment (TranceLove) [inline commons_compress_7z/src/main/java/com/amaze/filemanager/filesystem/compressed/sevenz/SevenZFile.java:2122]: Prefer not using `@Nullable` that is not from official Android SDK. Better pull it off at all.

**Comment by TranceLove** [comment]
Bit weird they are not seeing this at upstream commons-compress library, even in their current `master`

https://github.com/apache/commons-compress/blob/bc50be9fcabd1260afe7b66e631316ae6ecdab7d/src/main/java/org/apache/commons/compress/archivers/sevenz/AES256SHA256Decoder.java#L74-L85

Decent to trap this exception to prevent crash IMO.

**Review by VishalNehra — APPROVED** [review]
