### PR TITLE
Fix parsing SSH URLs with special characters included

### LINKED ISSUE #1290: Support Robolectric tests that use CryptUtil
Currently `AndroidKeyStore` is required by `CryptUtil` to generate keys, and this restrict tests that depend on it must use Espresso and Android devices/emulators which are heavy.

We may need to find a way to make AndroidKeyStore available even on Robolectric tests.

### LINKED ISSUE #1333: Parsing problem with SFTP server path from database
[A review](https://forum.xda-developers.com/showpost.php?p=76963297&postcount=654) from one of XDA's user, scanno
His logs:

```
07-02 12:47:24.682 W/Uri (27485): Error parsing port string. 
07-02 12:47:24.682 W/Uri (27485): java.lang.NumberFormatException: For input string: "***" 
07-02 12:47:24.682 W/Uri (27485): at java.lang.Integer.parseInt(Integer.java:608) 
07-02 12:47:24.682 W/Uri (27485): at java.lang.Integer.parseInt(Integer.java:643) 
07-02 12:47:24.682 W/Uri (27485): at android.net.Uri$AbstractHierarchicalUri.parsePort( Uri.java:1136) 07-02 12:47:24.682 W/Uri (27485): at android.net.Uri$AbstractHierarchicalUri.getPort(Ur i.java:1115) 
07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.filesystem.ssh.SshConnection Pool.create(SshConnectionPool.java:180) 
07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.filesystem.ssh.SshConnection Pool.create(SshConnectionPool.java:173) 
07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.filesystem.ssh.SshConnection Pool.getConnection(SshConnectionPool.java:98) 07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.filesystem.ssh.SshClientUtil s.execute(SshClientUtils.java:72)
 07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.filesystem.ssh.SshClientUtil s.execute(SshClientUtils.java:127) 
07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.filesystem.HybridFile.forEac hChildrenFile(HybridFile.java:732) 
07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.asynchronous.asynctasks.Load FilesListTask.doInBackground(LoadFilesListTask.jav a:131) 
07-02 12:47:24.682 W/Uri (27485): at com.amaze.filemanager.asynchronous.asynctasks.Load FilesListTask.doInBackground(LoadFilesListTask.jav a:62) 
07-02 12:47:24.682 W/Uri (27485): at android.os.AsyncTask$2.call(AsyncTask.java:333) 07-02 12:47:24.682 W/Uri (27485): at java.util.concurrent.FutureTask.run(FutureTask.jav a:266) 
07-02 12:47:24.682 W/Uri (27485): at java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java:1162) 07-02 12:47:24.682 W/Uri (27485): at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
 07-02 12:47:24.682 W/Uri (27485): at java.lang.Thread.run(Thread.java:764) 
07-02 12:47:24.684 E/SshClientUtils(27485): Error executing template method
 07-02 12:47:24.684 E/SshClientUtils(27485): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference 
07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.filesystem.ssh.SshConnection Pool.create(SshConnectionPool.java:182)
 07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.filesystem.ssh.SshConnection Pool.create(SshConnectionPool.java:173)
 07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.filesystem.ssh.SshConnection Pool.getConnection(SshConnectionPool.java:98) 07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.filesystem.ssh.SshClientUtil s.execute(SshClientUtils.java:72) 
07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.filesystem.ssh.SshClientUtil s.execute(SshClientUtils.java:127) 
07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.filesystem.HybridFile.forEac hChildrenFile(HybridFile.java:732) 
07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.asynchronous.asynctasks.Load FilesListTask.doInBackground(LoadFilesListTask.jav a:131) 
07-02 12:47:24.684 E/SshClientUtils(27485): at com.amaze.filemanager.asynchronous.asynctasks.Load FilesListTask.doInBackground(LoadFilesListTask.jav a:62) 
07-02 12:47:24.684 E/SshClientUtils(27485): at android.os.AsyncTask$2.call(AsyncTask.java:333) 
07-02 12:47:24.684 E/SshClientUtils(27485): at java.util.concurrent.FutureTask.run(FutureTask.jav a:266) 07-02 12:47:24.684 E/SshClientUtils(27485): at java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java:1162) 
07-02 12:47:24.684 E/SshClientUtils(27485): at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636) 
07-02 12:47:24.684 E/SshClientUtils(27485): at java.lang.Thread.run(Thread.java:764) 
```

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1333 (hopefully) and fixes #1290. At places where `Uri.parse()` cannot properly split the SSH server URI for authentication credentials, it is done by hand instead.

~~Writing~~Robolectric test case ~~was not possible due to #1290, and~~ included since Apache Sshd cannot be run on Android devices (physical/emulator) ~~so Espresso tests aren't possible either~~. ~~I had to test with the hard way - t~~Tested with Oneplus One running Slim7 (7.1.2) and Galaxy S2 running SlimLP (5.1.1), connecting to OpenSSH server running on Fedora Atomic Host.

Espresso test for `UtilsHandler` to make sure data saved to database is not truncated is included however.

Note: I suspect SMB implementation would be affected by such problem too, but since nobody is complaining so far, I'm following the rule of "if it ain't broken, don't fix it" - or in separate PR for next milestone.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java [hunk 1]
```diff
@@ -169,27 +169,24 @@ public void expungeAllConnections() {
...
-        return create(Uri.parse(url));
-    }
-
     // Logic for creating SSH connection. Depends on password existence in given Uri password or
     // key-based authentication
-    private SSHClient create(@NonNull Uri uri) {
-        String host = uri.getHost();
-        int port = uri.getPort();
+    private SSHClient create(@NonNull String url) {
+        String host = url.substring(url.lastIndexOf('@')+1, url.lastIndexOf(':'));
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java]: You are just assuming that the "URI" (a String) passed is in the correct format, without any checks. If a "malformed URI" (by this method's definition) gets to here, the error will be difficult to track down, maybe add a RegEx check (and crash with the String explicited in the exception message)? Or check manually if the String has the required parts?

**Comment by EmmanuelMess** [comment]
If we are going to implement the parsing of SSH URIs by hand, maybe a RAIer implementation will be less error prone, what I mean is, have a special parsing immutable object that checks that the string is parsable and then parses it to final fields.

File: app/src/test/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPoolTest.java [hunk 2]
```diff
@@ -60,14 +74,116 @@ public void testGetConnectionWithUsernameAndKey(){
...
+        String validPassword = "testpassword";
+        createSshServer("testuser", validPassword);
+        saveSshConnectionSettings("testuser", validPassword, null);
+        assertNotNull(SshConnectionPool.getInstance().getConnection("ssh://testuser:testpassword@127.0.0.1:22222"));
+        assertNull(SshConnectionPool.getInstance().getConnection("ssh://invaliduser:invalidpassword@127.0.0.1:22222"));
+    }
+
+    //Sorry but this is not getting through yet...
+//    @Test @Ignore
+//    public void testGetConnectionWithUrlAndKeyAuth() throws IOException {
```
Comment (EmmanuelMess) [inline app/src/test/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPoolTest.java]: Please add explanation or delete the code.

**Comment by TranceLove** [comment]
> If we are going to implement the parsing of SSH URIs by hand, maybe a RAIer implementation will be less error prone, what I mean is, have a special parsing immutable object that checks that the string is parsable and then parses it to final fields. As opposed to just creating ad hoc code in a bunch of classes.

Agreed. I think time for making change is a bit tight for RC2... but can be done for final release.

File: app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java (hunk 1 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java]: Surely a regex based implementation would be nice, but will need time to make a good regex - the regex I found with RFC2396 compliance doesn't parse URIs having `@`, `#` nicely, and that's the reason why I had to split the string by hand.

(That I think it's already a non-compliant URI)

**Comment by EmmanuelMess** [comment]
> but can be done for final release.

You mean 3.4.0? Because the last release candidate that works IS the final release.

**Comment by TranceLove** [comment]
> You mean 3.4.0? Because the last release candidate that works IS the final release.

3.3.0 of course.

File: app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java [hunk 3]
```diff
@@ -236,4 +227,40 @@ private boolean validate(@NonNull SSHClient client) {
...
+     *
+     * <code>Uri.parse()</code> only parse URI that is compliant to RFC2396, but we have to deal
+     * with URI that is not compliant, since usernames and/or strong passwords usually have special
+     * characters included, like <code>ssh://user@example.com:P@##w0rd@127.0.0.1:22</code>.
+     *
+     * A design decision to keep database schema slim, by the way... -TranceLove
+     */
+    static class ConnectionInfo {
+
+        final String host;
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/filesystem/ssh/SshConnectionPool.java]: These fields should all be final.

**Comment by VishalNehra** [comment]
@TranceLove I check with SMB and including such symbols as password in SMB connection have no such problems. 
Will check this PR tomorrow.

**Comment by VishalNehra** [comment]
Unable to get the authentication done.
Initial addition of connection gets loaded correctly but after subsequent restarts of Amaze it doesn't accept the passphrase when the error toast of unable to authenticate.
What's strange is that passphrase is simple 'test' and I can reproduce this behavior in master too.
Can you please check and confirm @TranceLove 
LInk to [keys](https://drive.google.com/open?id=1DWPylxP3OSmclfpBUvIln7BVTpc-5slE) I used.

**Comment by TranceLove** [comment]
@VishalNehra When I run the key against sshj library alone I still get
```
[Previous stacktrace truncated]
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at net.schmizz.sshj.userauth.keyprovider.PuTTYKeyFile.decrypt(PuTTYKeyFile.java:292)
```
I suspected it might be the same at sshj upstream... but very sorry there's little I can do at this moment. I'll need more time to pinpoint the problem before the problem can be fixed (and maybe sshj as well).

**Comment by VishalNehra** [comment]
@TranceLove there's no hurry. Take your time.. meanwhile I'll test some more. BTW I'm using puttygen from WinSCP to generate keys, and they're working fine for me.

**Comment by VishalNehra** [comment]
@TranceLove considering this PR is not the root cause of the issue I'm facing and this does fix the problem it was intended to fix. Also we had planned RC2 today, I'll create a separate issue and approve this PR. 
You can work on my issue later in another RC scheduled for next week. 
What do you think?

**Comment by EmmanuelMess** [comment]
I added the "do not merge" tag because the PR has two approvals, but it seemed you found a bug, do remove when the problem is no more.
