### PR TITLE
Fix cloud connection authentication getting fired up again and again

### LINKED ISSUE #720: Move CloudAsyncTask out of MainActivtity
Move CloudAsyncTask out of MainActivtity, [here](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L2583). Also, if possible, the [LoaderCallbacks](https://github.com/TeamAmaze/AmazeFileManager/blob/master/app/src/play/java/com/amaze/filemanager/activities/MainActivity.java#L2500). That will free some space in the 2800 lines file.

### LINKED ISSUE #1394: Unable to add cloud connections
@EmmanuelMess please try to minimize much code refactoring. It's causing unwanted introduction of bugs. 
I'm unable to add any cloud connection. As soon as i authenticate and return back to Amaze, it re-initiates the authentication. 
I can't say where this bug was introduced.

### PR DESCRIPTION
**Pull request by VishalNehra**
Fixes #1394 
Fixes #720

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java [hunk 1]
```diff
@@ -1898,232 +1905,14 @@ public void onLoadFinished(Loader<Cursor> loader, final Cursor data) {
...
-                                Toast.makeText(MainActivity.this, getResources().getString(R.string.cloud_error_failed_restart),
-                                        Toast.LENGTH_LONG).show();
-                                return false;
-                        }
-                    } while (data.moveToNext());
-                }
-                return hasUpdatedDrawer;
-            }
+        if (mCloudCursorData != null && mCloudCursorData == data) return;
+        mCloudCursorData = data;
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: > [...]
> The Loader will release the data once it knows the application
> is no longer using it.  For example, if the data is
> a {@link android.database.Cursor} from a {@link android.content.CursorLoader},
> you should not call close() on it yourself.  If the Cursor is being placed in a
> {@link android.widget.CursorAdapter}, you should use the
> {@link android.widget.CursorAdapter#swapCursor(android.database.Cursor)}
> method so that the old Cursor is not closed.
> [...]

-- [onLoadFinished() documentation](https://developer.android.com/reference/android/app/LoaderManager.LoaderCallbacks.html#onLoadFinished(android.content.Loader%3CD%3E,%20D))

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java [hunk 2]
```diff
@@ -1189,6 +1193,8 @@ protected void onDestroy() {
         utilsHandler.close();
         cloudHandler.close();
 
+        if (mCloudCursorData != null) mCloudCursorData.close();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: > [...]
> The Loader will release the data once it knows the application
> is no longer using it.  For example, if the data is
> a {@link android.database.Cursor} from a {@link android.content.CursorLoader},
> you should not call close() on it yourself.  If the Cursor is being placed in a
> {@link android.widget.CursorAdapter}, you should use the
> {@link android.widget.CursorAdapter#swapCursor(android.database.Cursor)}
> method so that the old Cursor is not closed.
> [...]

-- [onLoadFinished() documentation](https://developer.android.com/reference/android/app/LoaderManager.LoaderCallbacks.html#onLoadFinished(android.content.Loader%3CD%3E,%20D))

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java [hunk 3]
```diff
@@ -0,0 +1,289 @@
...
+
+    @Override
+    @NonNull
+    public Boolean doInBackground(Void... voids) {
+        boolean hasUpdatedDrawer = false;
+
+        if (data == null) return false;
+        if (data.getCount() > 0 && data.moveToFirst()) {
+            do {
+                if (mainActivityWeakReference.get() == null) cancel(true);
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java]:
```java
final T t = this.t.get();
if(t != null) cancel(true);
```
Please

And you still need to exit the function if you want to.

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java [hunk 4]
```diff
@@ -0,0 +1,289 @@
...
+                if (isCancelled()) cancel(true);
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java]: > Attempts to cancel execution of this task. This attempt will fail if the task has already completed, already been cancelled, or could not be cancelled for some other reason.
> [...]

-- [AsyncTask.cancel() documentation](https://developer.android.com/reference/android/os/AsyncTask.html#cancel(boolean))

And you still need to exit the function if you want to.

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java [hunk 5]
```diff
@@ -0,0 +1,289 @@
...
+    protected void onCancelled() {
+        super.onCancelled();
+        mainActivityWeakReference.get().getSupportLoaderManager().destroyLoader(MainActivity.REQUEST_CODE_CLOUD_LIST_KEY);
+        mainActivityWeakReference.get().getSupportLoaderManager().destroyLoader(MainActivity.REQUEST_CODE_CLOUD_LIST_KEYS);
+    }
+
+    @Override
+    public void onPostExecute(@NonNull Boolean result) {
+        if (result) {
+            mainActivityWeakReference.get().getDrawer().refreshDrawer();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java]: This might NPE.

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java [hunk 6]
```diff
@@ -0,0 +1,289 @@
...
+                }
+            } while (data.moveToNext());
+        }
+        return hasUpdatedDrawer;
+    }
+
+    @Override
+    protected void onCancelled() {
+        super.onCancelled();
+        mainActivityWeakReference.get().getSupportLoaderManager().destroyLoader(MainActivity.REQUEST_CODE_CLOUD_LIST_KEY);
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/CloudLoaderAsyncTask.java]: This might NPE.

**Comment by EmmanuelMess** [comment]
PS:
I was ill and working on projects for school for most of this week, so I wasn't able to look at any GitHub notification...and they accumulated quite a bit. I'm able to work now, so I apologize for the lateness.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 1 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: We don't need the old cursor, this is just a hack to know if the request is a duplicate one. I couldn't find a proper solution to this for the time being.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 2 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: We don't need the old cursor, this is just a hack to know if the request is a duplicate one. I couldn't find a proper solution to this for the time being.
Can safely close the cursor, as we're not actively using it in any adapter.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: It doesn't say anywhere that this is a hack, and why it was implemented, what other solutions would be and why they don't work.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 2 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: Closing this cursor is undefined behaviour, you can't.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 1 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: onLoadFinished gets fired up again and again, without any reason. Simply try adding any cloud connection, pause Amaze and resume, onLoadFinished will get called for no reason. 
I figured this issue is a release blocker, also I am quite low on time myself.
So I wrote this to delegate these duplicate callbacks and this gets the job done. 
If you can find a real solution to this, I'll gladly accept your PR,

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 2 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: What? It's the original cursor which extends this undefined behaviour and is automatically handled by LoaderManager. This is a different cursor, a copy of the original one. It's my responsibility to empty this.

**Comment by VishalNehra** [comment]
New commits added, per suggested by @EmmanuelMess 
Please review @EmmanuelMess and @TranceLove

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: I had made a [patch](https://gist.github.com/EmmanuelMess/8aabccfc7e3c213b33f03873d58d8cef) a while ago for an older version of master, what did you think of it. Because of the nature of the patch I couldn't know if it was just me not being able to replicate, or the issue being fixed.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 2 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: @1909 you are getting a strong reference, not a copy, it is literally the same cursor.

**Comment by VishalNehra** [comment]
@TranceLove confirm if you get these duplicate connections after the initial setup, i.e. after subsequent Amaze restarts, once the connection is successfully authenticated.

**Comment by VishalNehra** [comment]
@TranceLove multiple accounts of same service is not supported. You can try adding, it should show some error.
Anyways. as for the problems you mentioned, I am aware. Can create separate issues for them.
I tried fixing them. This duplication occured even after adding new connection. I managed to fix that, but I couldn't fix this.
For now, this PR does fix what it is intended to (see the original issue).

**Comment by VishalNehra** [comment]
@TranceLove 
> However, one more symptom before I go regarding duplicated cloud connection entries: switching between Amaze and home screen/other apps will cause cloud connections to duplicate in the drawer.

Doesn't happen to me. No duplicate entries after successfully adding a new cloud connection and restarting Amaze.

> Seems the title of the pull request "Fix cloud connection authentication getting fired up again and again" cannot be applied here, since I did had authentication dialog fired up a few times on setting things up

This happened for you while setting up Dropbox account through Google credentials, right?
I didn't test this method. Will check on it. 
Please confirm if authentication dialog gets fired up during normal login of other services for you.

File: app/src/main/java/com/amaze/filemanager/activities/MainActivity.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/MainActivity.java]: > If you can find a real solution to this, I'll gladly accept your PR,

I have 6 PRs stuck, please start reviewing if you want my help with this. I will start working on this ASAP if you review them.

**Comment by TranceLove** [comment]
Weird. With today's master merge with this changeset, the problems mentioned above (duplicated entries, authentication dialog repeatedly fired up) disappeared.

* Tested with Oneplus 2 running Slim7 (7.1.2), everything is OK
* Tested with Samsung Galaxy S2 (GT-i9100) running SlimLP (5.1.1) duplicated entries symptom still occur when switching between apps; but after kill app everything is fine

I think I can give +1 now.

**Comment by VishalNehra** [comment]
I can also confirm, adding new Dropbox account with 'Sign in using Google' doesn't fire authentication again. It just happen once. 
I think for now, this is our best bet unless we can fully understand what's going on with ````onLoadFinished```` and Loaders in general.

**Comment by VishalNehra** [comment]
@EmmanuelMess ?

**Comment by EmmanuelMess** [comment]
I am not accepting this until change requests are dealt with.

**Comment by EmmanuelMess** [comment]
[This](https://github.com/TeamAmaze/AmazeFileManager/pull/1462#discussion_r224947661), [this](https://github.com/TeamAmaze/AmazeFileManager/pull/1462#discussion_r224947693), [this](https://github.com/TeamAmaze/AmazeFileManager/pull/1462#discussion_r225308802) (only the "document the hack thoroughly" part), [this](https://github.com/TeamAmaze/AmazeFileManager/pull/1462#discussion_r224947884).

**Comment by VishalNehra** [comment]
I've fixed them with 1f9ebb and 16d090

**Comment by EmmanuelMess** [comment]
```mainActivityWeakReference.get() != null``` makes no sense, if you don't have a strong reference the ```WeakReference``` might be garbage collected anytime.

As I said [here](https://github.com/TeamAmaze/AmazeFileManager/pull/1462#discussion_r224947861) use this pattern:
```java
final T t = this.t.get();
if(t != null) cancel(true);
```

And as I said:

> *The thing I am most adamant about is not having too many hacks in the app, commenting the hacks thourouly should add enough work for the hack to not be the *least effort* solution. Documentation [example](https://github.com/TeamAmaze/AmazeFileManager/blob/4f77ded154ea4d64069b04ca2bde56a92e9397da/app/src/main/java/com/amaze/filemanager/ui/views/drawer/CustomNavigationView.java#L104-L119).

I don't think this has been fixed yet.

**Comment by VishalNehra** [comment]
> mainActivityWeakReference.get() != null makes no sense, if you don't have a strong reference the WeakReference might be garbage collected anytime.

Can you please point to any source which justifies your statement? Because this has already introduced much redundant code.

**Comment by EmmanuelMess** [comment]
> Can you please point to any source which justifies your statement? Because this has already introduced much redundant code.

[Source](https://developer.android.com/reference/java/lang/ref/WeakReference):

> Suppose that the garbage collector determines at a certain point in time that an object is [weakly reachable](https://developer.android.com/reference/java/lang/ref/package-summary#reachability). At that time it will atomically clear all weak references to that object and all weak references to any other weakly-reachable objects from which that object is reachable through a chain of strong and soft references. At the same time it will declare all of the formerly weakly-reachable objects to be finalizable. At the same time or at some later time it will enqueue those newly-cleared weak references that are registered with reference queues.

If you are going to use an object first strongly reach it, then test if the object wasn't GC'd beforehand, and if not maintain it strogly reached until you don't need it anymore.
WeakRef -> StrongRef -> check -> use -> StrongRef out of scope -> repeat if needed.

**Comment by VishalNehra** [comment]
Done

**Comment by VishalNehra** [comment]
If you're talking about #1403 then I've a pending review there. I'll accept once you reply to it. 

The strong ref will automatically be GC'd

**Comment by EmmanuelMess** [comment]
> The strong ref will automatically be GC'd

Not until the object is destroyed.

**Comment by TranceLove** [comment]
Tested with Oneplus running Slim7 (7.1.2), authentication dialog still doesn't repeatedly fired up for Google Drive, Dropbox and One Drive. The problem that repeated cloud connection items came up at the drawer came back, untill restarting Amaze... but I think it's acceptable to take care of this in an separate issue.

Good to go.
