### PR TITLE
Fixes #3886

### LINKED ISSUE #3886: NPE when pasting a deleted/modified file
**Describe the bug**
I copy the file and want to paste it, to avoid the duplicate file names, I rename the file, but the  error is happen in paste operation.

**To Reproduce**
1. Copy the file
2. Delete(Rename) the file
3. click Paste
4. The crash happen

**Screenshots**
   

**Smartphone (please complete the following information):**
- Device: Google Pixel 5
- OS: Android 7.1.1
- Rooted: No
- Version: 3.8.5

**Crash logs**
```
[AsyncTask #9        ] Got exception checkout: /storage/emulated/0/DCIM/GrowTracker/2023-07-09-05-34-03/Text.txtjava.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri androidx.documentfile.provider.DocumentFile.getUri()' on a null object reference
	at com.amaze.filemanager.filesystem.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:166)
	at com.amaze.filemanager.filesystem.files.GenericCopyUtil.copy(GenericCopyUtil.java:316)
	at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:522)
	at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:406)
	at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:270)
	at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:237)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

### PR DESCRIPTION
**Pull request by yatiksihag01**
## Description
Disabled file modification while the copy/paste snackbar is visible. This behavior is expected, and it is implemented in almost all popular file manager apps. When users choose to paste a file into the same folder from which they copied it, they will be presented with the option to Rename & Save. This option will automatically append (1), (2), etc., at the end of the file name and save it.

#### Issue tracker   
Fixes #3886 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

- Device: Samsung Galaxy A13
- OS: Android 13

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java [hunk 1]
```diff
@@ -976,6 +993,20 @@ private void bindViewHolderGrid(@NonNull final ItemViewHolder holder, int positi
 
     holder.baseItemView.setOnLongClickListener(
         p1 -> {
+          MainActivityActionMode mainActivityActionMode =
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java:996]: Can you create a function to avoid code duplication?

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/PrepareCopyTask.java [hunk 2]
```diff
@@ -321,6 +330,29 @@ private void replaceFiles(
...
+    int appendInt = 1;
+    String newName;
+    File targetFile;
+
+    int conflictingFileIndex = filesToCopy.indexOf(conflictingFiles.get(0));
+    String oldName = filesToCopy.get(conflictingFileIndex).getName();
+    do {
+      newName =
+          oldName.substring(0, oldName.lastIndexOf("."))
+              + "("
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/PrepareCopyTask.java:345]: @TranceLove  @VishnuSanal your inputs here. Do we have a library or a utility class that we can utilise for this?

**Review by VishalNehra — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/PrepareCopyTask.java (hunk 2 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/PrepareCopyTask.java:345]: Related #2078 sorry but still need some time to work on it.

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
@yatiksihag01 hi, great work! here are some things I noticed:

- currently, the renaming works only for files. if I try to copy a directory & paste it, it renames every file inside of that folder - which is not the expected behavior; the directory simply should be renamed instead.

**Comment by yatiksihag01** [comment]
@VishnuSanal thanks for your feedback and for pointing out the issue. Sorry for the oversight, I'll try to make the necessary changes asap.

**Comment by yatiksihag01** [comment]
Hi @VishnuSanal in this commit I've made following changes:
* Pasting in the same directory with a conflicting non-directory file (e.g. images, videos etc.) will prompt a rename or skip choice.
* Move operation in same directory is restricted.
* If the conflicting file is a directory, it's automatically renamed and saved without showing any dialog. This workaround avoids the complexity of showing a dialog in this scenario, as it would require significant changes. Because during tree creation, the original conflicting directory is already removed and a new node is created. And now all the files and subdirectories under this new node behave as conflicting entities. Ig this approach offers the best solution. I'm open to any suggestions or feedback you might have.

**Comment by VishnuSanal** [comment]
@yatiksihag01 awesome! i will review the PR in a while.

**Review by VishnuSanal — CHANGES_REQUESTED** [review]
@yatiksihag01 awesome work! operation with files works great as expected! I noticed some glitches on working with directories:

- moving/copying a file from a path to another path simply falls back to the previous implementation (i.e, skip, overwrite, cancel). the dialog appears for every file within, if a directory is moved/copied.
- can you think of a solution to fix the creation of empty directories within?

**Comment by yatiksihag01** [comment]
Hi @VishnuSanal,
* As I explained in my previous comment, when conflicting file is a directory, the original conflicting directory gets removed and a new node is created. And now all the files and subdirectories under this new node behave as conflicting files. This problem is even with stable version of app. So we've two choices, either we simply rename and save conflicting directories without showing any dialog or explore an entirely new implementation using Kotlin, maybe using `suspendCancellableCoroutine` or something else I'm not sure.
* I haven't fully investigated the `mkdirs()` bug yet, as I wasn't sure whether there's an existing open issue and if someone is fixing it. I'll try to fix it.

**Comment by yatiksihag01** [comment]
Actually the duplicate subdirectory issue was caused by the wrong `HybridFile` constructor I used. I resolved this issue and also documented the `MakeDirectoryOperation.mkdirs()` method to provide guidance for future developers.

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/PrepareCopyTask.java (hunk 2 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/movecopy/PrepareCopyTask.java]: You may want to see if #3913 can help.

**Comment by VishnuSanal** [comment]
I tested here & there were some unexpected behaviors; I'll post a detailed review comment in a while.

**Comment by yatiksihag01** [comment]
@VishnuSanal, I still have some work to do, but please tell about the unexpected behavior you encountered.

**Comment by VishnuSanal** [comment]
> `@VishnuSanal`, I still have some work to do, but please tell about the unexpected behavior you encountered.

i see. I basically wasn't able to rename. copying & moving from a different directory prompted me a dialog, clicking on 'rename' resulted in a Toast message saying 'no file overwritten' (both files & directories). copying from the same directory resulted in the same too. moving to the same directory resulted in the new operation not permitted Toast message.

**Comment by yatiksihag01** [comment]
@VishnuSanal I fixed the issues you mentioned. There are still [these](https://github.com/TeamAmaze/AmazeFileManager/pull/3913#issuecomment-1708857490) bugs to be resolved by @TranceLove.  And when user try to move the files in same directory they should see this toast message as it doesn't makes any sense to do so.

**Comment by VishalNehra** [comment]
@yatiksihag01 please see and resolve the static code analysis errors in the build
https://github.com/TeamAmaze/AmazeFileManager/pull/3898/checks?check_run_id=16643918735

**Comment by yatiksihag01** [comment]
@VishalNehra One error in static code analysis is about `showDialog()` function length. I can reduce the length but it'll add unnecessary complication. So should I do that?

**Comment by VishalNehra** [comment]
Yes please

**Comment by VishalNehra** [comment]
@VishnuSanal  please review here

**Comment by VishalNehra** [comment]
You're not using filenamehelper from #3913  ?

**Review by VishnuSanal — APPROVED** [review]
great job! works as expected. operations I tested:

- moving to the same directory
   - "same destination & source Toast" (both for directories & files)
- copying to the same directory
   - works as expected (both for directories & files)
- copying/moving from another directory
   - directory: works as expected
   - file: works as expected most of the times; but when I rename the source folder & try copy/cut & paste again, renaming fails. if cut option is selected, the source files are getting deleted.

approving this for merge for now, since failure is happening only on an edge case (which most users wouldn't even notice, IMO) - @yatiksihag01 you can fix this in this PR if you can figure out why this happens from the top of your head, else, we can have a new issue & you can fix it later as you wish.

awesome work, once again!

(PS: sorry for the delayed review 😔)

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Write to us on telegram for a bounty on this issue thanks again for contributing 🙂

**Comment by yatiksihag01** [comment]
> file: works as expected most of the times; but when I rename the source folder & try copy/cut & paste again, renaming fails. if cut option is selected, the source files are getting deleted.

Hi @VishnuSanal, appreciate your feedback and approval. Could you provide more details on the issue and steps to reproduce it? Kindly open an issue and assign it to me. I'll work on a fix soon.

**Comment by yatiksihag01** [comment]
Hi @VishalNehra, thank you for your kind offer of a bounty for my contribution but I did not expect any monetary rewards for this PR. I'm grateful for the opportunity to have contributed to the project:)
