### PR TITLE
Fixes #2417

### LINKED ISSUE #2417: Cant open OPEN_DOCUMENT_TREE intent when triggering SAF
## Issue explanation (write below this line)

Not sure why this keeps happening all access permissions have been granted,
it really began with cloud plugin but without it app doesnt function.

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux Android 9 - 25
* __Device:__ p281
* __Model:__ TV-BOX
* __Product:__ p281
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle
Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
at
android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
at android.app.Activity.startActivityForResult(Activity.java:4228)
at
androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
at android.app.Activity.startActivityForResult(Activity.java:4186)
at
androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
at
com.amaze.filemanager.utils.MainActivityHelper.triggerStorageAccessFramework(MainActivityHelper.java:301)
at
com.amaze.filemanager.utils.MainActivityHelper.lambda$guideDialogForLEXA$4(MainActivityHelper.java:291)
at
com.amaze.filemanager.utils.MainActivityHelper.lambda$guideDialogForLEXA$4$MainActivityHelper(MainActivityHelper.java)
at
com.amaze.filemanager.utils.-$$Lambda$MainActivityHelper$UwhrA_yD3ZmiyefJq6Wf47pqvKg.onClick(lambda)
at
com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
at android.view.View.performClick(View.java:5637)
at android.view.View$PerformClick.run(View.java:22429)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6125)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes #2417

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

- Device: Pixel 3A
- OS: Android Tiramisu x86_64
- Device: Realme Narzo 20A
- OS: Android 11

#### Build tasks success
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/views/drawer/Drawer.java [hunk 1]
```diff
@@ -806,7 +807,13 @@ public boolean onNavigationItemSelected(@NonNull MenuItem item) {
               .setOnClickListener(
                   (v) -> {
                     Intent safIntent = new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);
-                    mainActivity.startActivityForResult(safIntent, MainActivity.REQUEST_CODE_SAF);
+
+                    if (safIntent.resolveActivity(mainActivity.getPackageManager()) != null)
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/views/drawer/Drawer.java:811]: Remember to add the curly brackets on ifs as per the guidelines

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]
You should use a Snackbar if a view is available.

File: app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt [hunk 2]
```diff
@@ -449,28 +460,40 @@ class FtpServerFragment : Fragment(R.layout.fragment_ftp) {
...
-                                                    "com.android.externalstorage.documents",
-                                                    "primary:" +
-                                                        directoryUri
-                                                            .substringAfter(
-                                                                defaultPathFromPreferences
-                                                            )
+                            .onPositive(fun(dialog: MaterialDialog, _: DialogAction) {
+                                val intent = Intent(Intent.ACTION_OPEN_DOCUMENT_TREE)
+
+                                if (intent.resolveActivity(mainActivity.packageManager) != null) {
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/FtpServerFragment.kt:466]: Can you create a kotlin extension function on `Intent` instead of writing if else conditions everywhere please? Take callbacks as args.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]

File: app/src/main/java/com/amaze/filemanager/ui/Extensions.kt [hunk 3]
```diff
@@ -112,3 +115,15 @@ fun View.showFade(duration: Long) {
     this.animate().alpha(1f).duration = duration
     this.visibility = View.VISIBLE
 }
+
+fun Intent.runIfDocumentsUIExists(mainActivity: MainActivity, callback: Runnable) {
```
[the remark this answers is not in the document]
Comment (VishnuSanal) [reply app/src/main/java/com/amaze/filemanager/ui/Extensions.kt]: > Avoid passing mainActivity instance too much

Okay, I did it here cuz I didn't find any other way to get a `View` to show a `SnackBar`
