### PR TITLE
Bugfix/2002

### LINKED ISSUE #2002: Unable to open files when folder has too much content
**Describe the bug**
Unable to image files through gallery

**To Reproduce**
Had over 8k images in a folder and try to open an image throwing a crash.

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - OS: Android 10
 - Rooted: No
 - Version: 3.5.3

**Additional context**

Stacktrace 

```
2020-10-08 20:54:52.768 28345-28345/com.amaze.filemanager.debug E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 6622424)
2020-10-08 20:54:52.769 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo: Bundle stats:
2020-10-08 20:54:52.772 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:   android:viewHierarchyState [size=7120]
2020-10-08 20:54:52.774 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:     android:views [size=7072]
2020-10-08 20:54:52.775 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:       0x7f09017e [size=2864]
2020-10-08 20:54:53.310 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:   android:support:fragments [size=6614472]
2020-10-08 20:54:53.311 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo: PersistableBundle stats:
2020-10-08 20:54:53.311 28345-28345/com.amaze.filemanager.debug W/ActivityStopInfo:   [null]
2020-10-08 20:54:53.311 28345-28345/com.amaze.filemanager.debug D/AndroidRuntime: Shutting down VM
2020-10-08 20:54:53.316 28345-28345/com.amaze.filemanager.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amaze.filemanager.debug, PID: 28345
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 6622424 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7643)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.os.TransactionTooLargeException: data parcel size 6622424 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:550)
        at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4564)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7643) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-10-08 20:54:53.358 28345-28345/com.amaze.filemanager.debug I/Process: Sending signal. PID: 28345 SIG: 9

```

### LINKED ISSUE #2004: Opening Amaze doesn't restore the last opened path on either tabs
**Describe the bug**
Opening Amaze doesn't restore the last opened path on either tabs

**To Reproduce**
1. Open any paths on both tabs.
2. Close Amaze
3. Open again, both tabs open with default paths.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - OS: Android 10

**Additional context**

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2002 
Fixes #2004 
-or-   
Addresses #

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: oneplus 6t
- OS: android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Comment by TranceLove** [comment]
Fix for #2002 verified on GPD XD running LegacyROM (4.4.4), Samsung Galaxy S2 running SlimLP (5.1.1), Oneplus 2 running AOSPExtended (7.1.2) and Fairphone 3 running LineageOS 16.0(9.0), against a folder full of screenshots from FinalBurn Neo which means a total of >13000 images. On the mentioned devices all could return to app without crash from gallery app.

File: app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java [hunk 1]
```diff
@@ -215,21 +213,10 @@ public void onCreate(Bundle savedInstanceState) {
...
-      }
-    }
-    adapter.stoppedAnimation = true;
-  }
-
   @Override
   public View onCreateView(
       LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
     rootView = inflater.inflate(R.layout.main_frag, container, false);
-    setRetainInstance(true);
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java:232]: Is this safe?

**Comment by TranceLove** [comment]
Fix for #2004 verified on Pixel 2 emulator running stock Android 10. Problem was not reproducible on my Oneplus 2 running AOSPExtended (7.1.2.) and Fairphone 3 running LineageOS 16.0 (9.0), sorry. But applying the changeset didn't cause regression either.

I'm voting +1 here. PR will only get through after @EmmanuelMess voted anyway.

**Review by TranceLove — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]
