### PR TITLE
#1856 Fix for app crashing when using save as option from browser

### LINKED ISSUE #1856: force close on "save as" option
**Describe the bug**
the "save as" option among android share options cause the app to break.

**To Reproduce**
1. Go to 'Firefox> Share'
2. Click on 'Save as...'
4. amaze file launches. as i select the floating button, it force closes.

**Expected behavior**
maybe amaze could've downloaded the content

**Smartphone (please complete the following information):**
 - Device: LG G4 H818P
 - OS: nougat
 - Rooted: no
 - Version: 3.4.3

**Additional context**
thanks for the app though.

### PR DESCRIPTION
**Pull request by pcsaunak**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1856 
-or-   
Addresses #

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: one plus 7
- OS: android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info
1. Created an additional utility function to create text files.
2. Created additional check in the existing ACTION_SEND intent. It will only go the new block when we are receiving an intent from browser.

### CODE REVIEW

**Comment by pcsaunak** [comment]
@VishalNehra Can you cross check this and let me know if you see any issues here?

**Comment by VishalNehra** [comment]
Great work! (:
A few things:
Please close #1955 as it's stale now.
Please fill details in this PR description, write Fixes #1856 (this will automatically close the issue on merging this PR).
Tick the checks in description, whichever you performed. Also write your device info in relevant field there.
Assign Projects -> roadmap -> click press outside, from dropdown select the release in which you want this to be pushed.

Just few non technical things and we're good to go! (:

File: app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java [hunk 1]
```diff
@@ -580,6 +584,23 @@ private void initFabToSave(final ArrayList<Uri> uris) {
...
                   finish();
                 }
+              } else {
+                Bundle extras = intent.getExtras();
+                String data =
+                    extras.getString(Intent.EXTRA_SUBJECT)
+                        + "\nURL: "
+                        + extras.getString(Intent.EXTRA_TEXT);
+                String fileName = Long.toString(System.currentTimeMillis());
+                FileUtil.mktextfile(data, getCurrentMainFragment().getCurrentPath(), fileName);
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/ui/activities/MainActivity.java:594]: If you notice, the call is sync, so saving the data occurs in main thread, which is not recommended. 
Please write this call around in runnable as follows.
```AppConfig.runInBackground(() -> FileUtil.mktextfile(data, getCurrentMainFragment().getCurrentPath(), fileName));```

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java [hunk 2]
```diff
@@ -619,6 +620,35 @@ public static boolean mkfile(final File file, Context context) {
...
+
+    File f = new File(path + "/" + fileName + ".txt");
+    FileOutputStream out = null;
+    OutputStreamWriter outputWriter = null;
+    if (f.exists()) {
+      f.delete();
+    }
+    try {
+      f.createNewFile();
+      out = new FileOutputStream(f);
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java:633]: Pass a second argument as false to FileOutputStream constructor, it'll overwrite instead of appending. No need to delete the file first.

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java [hunk 3]
```diff
@@ -619,6 +620,35 @@ public static boolean mkfile(final File file, Context context) {
     return false;
   }
 
+  public static boolean mktextfile(String data, String path, String fileName) {
+
+    File f = new File(path + "/" + fileName + ".txt");
+    FileOutputStream out = null;
+    OutputStreamWriter outputWriter = null;
+    if (f.exists()) {
+      f.delete();
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java:629]: Redundant call.

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]
