### PR TITLE
Null check on output stream and writer at FileUtil.mktextfile()

### LINKED ISSUE #2346: NPE on FileUtil::mktextfile : null OutputStreamWriter
## Issue explanation (write below this line)

why does this keep happening

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU9DTF1:user/release-keys 9 - 28
* __Device:__ dreamlte
* __Model:__ SM-G950F
* __Product:__ dreamltexx
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStreamWriter.close()' on a null object reference
 at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:50)
 at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
 at io.reactivex.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:40)
 at io.reactivex.Completable.subscribe(Completable.java:2309)
 at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
 at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStreamWriter.close()' on a null object reference
 at com.amaze.filemanager.filesystem.FileUtil.mktextfile(FileUtil.java:668)
 at com.amaze.filemanager.ui.activities.MainActivity.lambda$saveExternalIntentExtras$4(MainActivity.java:574)
 at com.amaze.filemanager.ui.activities.MainActivity.lambda$saveExternalIntentExtras$4$MainActivity(Unknown Source:0)
 at com.amaze.filemanager.ui.activities.-$$Lambda$MainActivity$ml8RfNUUkXkPbWWKYXN5nE_8Us4.run(Unknown Source:6)
 at io.reactivex.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:36)
 ... 10 more

```
</details>
<hr>

Raised by: vishal_nehra
Reporter: Smt88952

### PR DESCRIPTION
**Pull request by TranceLove**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2346

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishnuSanal — APPROVED** [review]
Looks good to me :)

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java [hunk 1]
```diff
@@ -655,21 +655,26 @@ public static boolean mktextfile(String data, String path, String fileName) {
...
+      Log.e(FileUtil.LOG, "Error writing file contents", io);
       return false;
     } finally {
-      try {
-        outputWriter.close();
-        out.flush();
-        out.close();
-      } catch (IOException e) {
-        Log.e(FileUtil.LOG, e.getMessage());
+      if (out != null && outputWriter != null) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java:670]: This if should be per line. if(x != null) x.close(); if(y != null) y.close();

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java [hunk 2]
```diff
@@ -655,21 +655,26 @@ public static boolean mktextfile(String data, String path, String fileName) {
...
-      outputWriter = new OutputStreamWriter(out);
-      outputWriter.write(data);
-      return true;
+      if (f.createNewFile()) {
+        out = new FileOutputStream(f, false);
+        outputWriter = new OutputStreamWriter(out);
+        outputWriter.write(data);
+        return true;
+      } else {
+        return false;
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java:664]: Are we sure we want to use the "finally executes before return"?

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]
See comments

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java (hunk 2 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java:664]: Any implications on using this? If we're to prevent leaks this seems a better way to go.

**Review by VishalNehra — APPROVED** [review]

**Comment by VishalNehra** [comment]
Could've fixed the `onError` callback that's not implemented as well.
`io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call.`

**Review by EmmanuelMess — APPROVED** [review]
