### PR TITLE
Fallback to webview URL if Google Play is not available

### LINKED ISSUE #1795: crash when get cloud plugin
**Describe the bug**
crash when get cloud plugin

**To Reproduce**
1. tap the floating button 'add'
2. tap 'Cloud Connection'
3. tap 'Get Cloud plugin'

**Expected behavior**
Show a dialog to give some information.

**Screenshots**
Screen Shot

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: Android 4.4.4
 - Rooted: No
 - Version: 3.3.2

**Additional context**

**Stack Trace**
Crash directly with the stack trace:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.amaze.filemanager, PID: 20664
                                                   android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.filemanager.amazecloud }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
                                                       at android.app.Activity.startActivityForResult(Activity.java:3424)
                                                       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
                                                       at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:233)
                                                       at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:825)
                                                       at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:939)
                                                       at android.support.v4.app.Fragment.startActivity(Fragment.java:1002)
                                                       at android.support.v4.app.Fragment.startActivity(Fragment.java:991)
                                                       at com.amaze.filemanager.fragments.CloudSheetFragment.onClick(CloudSheetFragment.java:133)
                                                       at android.view.View.performClick(View.java:4438)
                                                       at android.view.View$PerformClick.run(View.java:18422)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1795. Also moved corresponding URI to strings.xml.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/fragments/CloudSheetFragment.java [hunk 1]
```diff
@@ -129,8 +130,14 @@ public void onClick(View v) {
                 break;
             case R.id.linear_layout_get_cloud:
                 Intent cloudPluginIntent = new Intent(Intent.ACTION_VIEW);
-                cloudPluginIntent.setData(Uri.parse("market://details?id=com.filemanager.amazecloud"));
-                startActivity(cloudPluginIntent);
+                cloudPluginIntent.setData(Uri.parse(getString(R.string.cloud_plugin_google_play_uri)));
+                try {
+                    startActivity(cloudPluginIntent);
+                } catch (ActivityNotFoundException ifGooglePlayIsNotInstalled) {
+                    cloudPluginIntent = new Intent(Intent.ACTION_VIEW);
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/fragments/CloudSheetFragment.java]: This line seems redundant.

**Comment by TranceLove** [comment]
Two ticks, merge.
