### PR TITLE
Fix time format and organize imports

### LINKED ISSUE #1303: Negative remaining time
See "time remaining":

Seconds is negative and I think I've seen minutes go >60.

### PR DESCRIPTION
**Pull request by TranceLove**
Fixes #1303.

Tested on Oneplus 2 running Slim7 (7.1.2) copying files over SSH, extract zip and encrypt file.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 1]
```diff
@@ -241,8 +262,8 @@ public static int nthToLastCharIndex(int elementNumber, String str, char element
      * Formats input to plain mm:ss format
      */
     public static String formatTimer(long timer) {
-        final long min = TimeUnit.SECONDS.toMinutes(timer);
-        final long sec = TimeUnit.SECONDS.toSeconds(timer - TimeUnit.MINUTES.toMillis(min));
-        return String.format("%02d:%02d", min, sec);
+        final long min = timer / 60;
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java]: You seem to be doing exactly what was being done before, but in a more 'illegible' way. See ` TimeUnit.SECONDS.toMinutes(timer);`:

```
public long toMinutes(long d) { return d/(C4/C3); }// C4/C3 == 60L
```

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 2]
```diff
@@ -241,8 +262,8 @@ public static int nthToLastCharIndex(int elementNumber, String str, char element
...
+        final long sec = timer % 60;
+        return String.format(Locale.US, "%02d:%02d", min, sec);
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java]: Why are you hardcoding a locale? doesn't the Android System manage locales acordingly?

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 3]
```diff
@@ -241,8 +262,8 @@ public static int nthToLastCharIndex(int elementNumber, String str, char element
      * Formats input to plain mm:ss format
      */
     public static String formatTimer(long timer) {
-        final long min = TimeUnit.SECONDS.toMinutes(timer);
-        final long sec = TimeUnit.SECONDS.toSeconds(timer - TimeUnit.MINUTES.toMillis(min));
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java]: It seems that the timer was already in seconds. The mistake seems to be the `toMillis(min)`, it should be `toSeconds(min)`

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java [hunk 4]
```diff
@@ -241,8 +262,8 @@ public static int nthToLastCharIndex(int elementNumber, String str, char element
      * Formats input to plain mm:ss format
      */
     public static String formatTimer(long timer) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/Utils.java]: Nowhere does it say the timer is in seconds, I think that is what led to the original mistake.

File: app/src/main/java/com/amaze/filemanager/utils/Utils.java (hunk 2 above)
Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/utils/Utils.java]: Per recommendation from Android Studio's lint. As long as this is simply `mm:ss`, it should be fine.

Unless this will change to locale-specific strings (e.g. mm分ss秒 in Chinese)...

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/Utils.java]: > Per recommendation from Android Studio's lint. As long as this is simply `mm:ss`, it should be fine.
>
> Unless this will change to locale-specific strings (e.g. mm分ss秒 in Chinese)...

It should be fine, but I don't know what transformations Java does based on the locale, and would not like to introduce subtle bugs, irreplicable bugs (see section "Be wary of the default locale" [here](https://developer.android.com/reference/java/util/Locale)).

I see two solutions, using the `SimpleDateTime` class and using [this fix](https://stackoverflow.com/questions/14389349/android-get-current-locale-not-default) from StackOverflow. I would also accept that you return the code to String.format("%02d:%02d", min, sec) so that lint keeps on warning.
