### PR TITLE
Check for empty archive and toast user

### LINKED ISSUE #2659: App crashes when extracting an empty compressed file
**Describe the bug**
When attempting to extract an empty zip file, the application crashes. I assume this is not desired and that a dialogue should warn the user that they cannot extract empty zip files.

**To Reproduce**
1. Put an empty compressed file on phone
2. Attempt to extract compressed file with application

**Expected behavior**
A dialogue box should warn the user or, nothing should happen.

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS:  Android 11
 - Rooted: No
 - Version: 3.7

### PR DESCRIPTION
**Pull request by TranceLove**
Uses an Exception to notify `ExtractService` to Toast user for empty archives.

#### Issue tracker   
Fixes #2659

#### Automatic tests
- [x] Added test cases
  
#### Manual tests
- [x] Done  
  
- Device: Pixel 2 emulator
- OS: Android 11

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/AbstractCommonsArchiveExtractor.kt [hunk 1]
```diff
@@ -64,19 +64,24 @@ abstract class AbstractCommonsArchiveExtractor(
...
+                    listener.onUpdate(entry.name)
+                    // TAR is sequential, you need to walk all the way to the file you want
+                    while (entry.hashCode() != inputStream.nextEntry.hashCode()) {}
+                    extractEntry(context, inputStream, entry, outputPath)
+                }
             }
+            inputStream.close()
+            listener.onFinish()
+        } else {
+            inputStream.close()
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/compressed/extractcontents/helpers/AbstractCommonsArchiveExtractor.kt:82]: Shouldn't the stream close in a finally block?

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -715,5 +715,6 @@ You only need to do this once, until the next time you select a new location for
     <string name="ftp_preference_saf_filesystem_title">Use legacy filesystem</string>
     <string name="ftp_preference_saf_filesystem">Enable this for support for using device external storage on newer Android versions</string>
     <string name="ftp_server_fallback_path_reset_prompt">FTP server shared path had been resetted to internal storage as you are switching back to legacy filesystem implementation. Please select a new path using the menu on the top right as necessary.</string>
+    <string name="error_empty_archive">Archive \"%s\" is an empty archive.</string>
```
Comment (VishalNehra) [inline app/src/main/res/values/strings.xml:718]: `archieve` is twice? Maybe `failed to open emptt archive %s`

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]
