### PR TITLE
Bugfix/2087

### LINKED ISSUE #2087: Amaze can't remember default app in app chooser dialog
**Describe the bug**
Amaze can't remember default app to open a file. Choosing 'Always' on file chooser don't remember the app with which file was opened.

**Smartphone (please complete the following information):**
 - Device: Oneplus 6t
 - Android 10

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2087
-or-   
Addresses #

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Related PR  
Related to PR #

#### Additional Info

### CODE REVIEW

**Review by TranceLove — COMMENTED** [review]
Looks OK on Fairphone 3 running LineageOS 16.0 (9.0) and Samsung Galaxy S2 running SlimLP (5.1).

However, I wonder if it's possible to open the file directly if there is only one app available for the selected file?

**Comment by VishalNehra** [comment]
> Looks OK on Fairphone 3 running LineageOS 16.0 (9.0) and Samsung Galaxy S2 running SlimLP (5.1).
> 
> However, I wonder if it's possible to open the file directly if there is only one app available for the selected file?

Valid concern 🤔 For now need to choose 'Always' manually even if only one application is there. I think lot of logic need to be modified. Before showing the fragment need to query for intent apps. Maybe enhancement for later versions?

**Comment by TranceLove** [comment]
I'm good to go. +1.

**Review by TranceLove — DISMISSED** [review]

**Comment by EmmanuelMess** [comment]
> However, I wonder if it's possible to open the file directly if there is only one app available for the selected file?

As long as there is the "open as" option, I think this could be implemented.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java [hunk 1]
```diff
@@ -116,22 +121,40 @@ public View getView(final int position, View convertView, ViewGroup parent) {
...
     }
 
     final AppHolder holder = (AppHolder) view.getTag();
 
-    modelProvider.loadApkImage(rowItem.path, holder.apkIcon);
+    if (modelProvider != null) {
+      modelProvider.loadApkImage(rowItem.path, holder.apkIcon);
+    } else if (isBottomSheet) {
+      try {
+        holder.apkIcon.setImageDrawable(
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java:143]: This seems that it should be in Glide logic, not here.

File: app/src/main/java/com/amaze/filemanager/adapters/data/OpenFileParcelable.kt [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.amaze.filemanager.adapters.data
+
+import android.net.Uri
+import android.os.Parcel
+import android.os.Parcelable
+
+class OpenFileParcelable(
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/data/OpenFileParcelable.kt:27]: Use @parcelize for parcelables.

File: app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java [hunk 3]
```diff
@@ -404,7 +406,7 @@ public static void installApk(
   }
 
   private static void openUnknownInternal(
-      Uri contentUri, String type, Context c, boolean forcechooser, boolean useNewStack) {
+      Uri contentUri, String type, MainActivity c, boolean forcechooser, boolean useNewStack) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java:409]: Why is Context now Activity?

File: app/src/main/java/com/amaze/filemanager/ui/base/BaseBottomSheetFragment.kt [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+            // see recommendations on https://material.io/components/sheets-bottom#specs
+            dialog!!.window!!.setLayout(Utils.dpToPx(requireContext(), 450), -1)
+        }
+    }
+
+    /**
+     * Initializes bottom sheet ui resources based on current theme
+     */
+    fun initDialogResources(rootView: View) {
+        when ((activity as ThemedActivity?)!!.appTheme) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/base/BaseBottomSheetFragment.kt:48]: Missing AppTheme.LIGHT, please try to use "else" the least possible (someone that reads the code might not realize how many cases the "else" handles).

File: app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt [hunk 5]
```diff
@@ -0,0 +1,379 @@
...
+                return fragment
+            }
+
+        private fun startActivity(context: Context, intent: Intent) {
+            try {
+                context.startActivity(intent)
+            } catch (e: ActivityNotFoundException) {
+                Log.e(javaClass.simpleName, e.message, e)
+                Toast.makeText(context, R.string.no_app_found, Toast.LENGTH_SHORT).show()
+                throw e
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt:116]: Throw with no Throws annotation, my recomendation would be to make UI errors silent (or just a toast) and file errors crashy.

**Review by EmmanuelMess — APPROVED** [review]
Why does this change require so many changes?

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]
Ups, last is request changes

File: app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt (hunk 5 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt:116]: This is caught later on in `getPreferenceAndStartActivity`  in case some app which was earlier set default was uninstalled. We try to run with it and if that activity is not found then we show the chooser sheet again.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java (hunk 1 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java:143]: Not using glide for this bottom sheet, just the adapter.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java:143]: Why not? Glide should do most/all image showing. Should this be added as an issue and the PR accepted?

File: app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt (hunk 5 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt:116]: The Throws annotation is for the compiler to catch issues with non catched exceptions. To make sure each use case of this function catches this exception.

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java (hunk 1 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java:143]: I originally used glide but decided to remove it later due ti some reason. That reason is no more applicable, will add it again. Thanks for pointing.

File: app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java (hunk 3 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java:409]: I guess various underlying methods / static open file fragment calls need it.

File: app/src/main/java/com/amaze/filemanager/adapters/data/OpenFileParcelable.kt (hunk 2 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/data/OpenFileParcelable.kt:27]: kotlin-android-extensions is increasing gradle build time by quite some amount. Skipping it for now.

File: app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt (hunk 5 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt:122]: Throws still not forcing compiler to check the exception in kotlin.

**Comment by VishalNehra** [comment]
Build test apk

File: app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt (hunk 5 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/dialogs/OpenFileDialogFragment.kt:122]: Okay.

File: app/src/main/java/com/amaze/filemanager/adapters/data/OpenFileParcelable.kt (hunk 2 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/adapters/data/OpenFileParcelable.kt:27]: Is this a reported issue?

File: app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/adapters/AppsAdapter.java]: https://developer.android.com/kotlin/parcelize

**Comment by EmmanuelMess** [comment]
The code works, but please fix the parcelize issue.

**Review by EmmanuelMess — APPROVED** [review]
