### PR TITLE
Ask for permission before installing apk on API >= M

### LINKED ISSUE #1227: Can't install apps on Oreo
Since we don't explicitly ask for install permissions using the [new API](https://developer.android.com/studio/publish/#publishing-unknown) Amaze fails to install any apk file.

### PR DESCRIPTION
**Pull request by EmmanuelMess**
* Ask for permission before installing apk on API >= M
* Created PermissionsActivity for MainActivity

Fixes #1227.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/activities/superclasses/PermissionsActivity.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
+package com.amaze.filemanager.activities.superclasses;
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/activities/superclasses/PermissionsActivity.java]: It sounds a bit awkward to me that a superclass is placed below the subclass. However, it makes sense if it is heading for 3.3.0 since the blast radius will be too big if `MainActivity` should be placed below `PermissionsActivity`.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/superclasses/PermissionsActivity.java]: What do you mean "below"? Physically below in some visual representation or hierarchically below?

Comment (TranceLove) [reply app/src/main/java/com/amaze/filemanager/activities/superclasses/PermissionsActivity.java]: Hierarchically below.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/activities/superclasses/PermissionsActivity.java]: `MainActivity` extends `PermissionsActivity`, `MainActivity` is hierarchically below `PermissionsActivity`.
