### PR TITLE
FileUtils: call to OpenFileDialogFragment using explicit mime type

### LINKED ISSUE #2166: Mp3 files are recognized as a certificate or (nfc) tag
Steps to reproduce: just take any file, and rename it to filename.mp3 then try to open it. It will show you a few apps to open it. (like the certificate manager or the Tag manager) open the file with a app, and you get the error. 

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Android 10 - 29
* __Device:__ a51
* __Model:__ SM-A515F
* __Product:__ a51nseea
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.VIEW dat=content://com.amaze.filemanager/storage_root/storage/emulated/0/Download/stdout.mp3 typ=*/* flg=0x1 cmp=com.android.apps.tag/.TagViewer } from ProcessRecord{74f7f71 3139:com.amaze.filemanager/u0a510} (pid=3139, uid=10510) requires android.permission.NFC
	at android.os.Parcel.createException(Parcel.java:2088)
	at android.os.Parcel.readException(Parcel.java:2056)
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4454)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5203)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at android.app.Activity.startActivity(Activity.java:5587)
	at android.app.Activity.startActivity(Activity.java:5555)
	at com.amaze.filemanager.ui.dialogs.OpenFileDialogFragment$loadViews$$inlined$let$lambda$1.onClick(OpenFileDialogFragment.kt:344)
	at android.view.View.performClick(View.java:7862)
	at android.widget.TextView.performClick(TextView.java:15004)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1447)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:980)
	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2074)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)


```
</details>
<hr>

### PR DESCRIPTION
**Pull request by TranceLove**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2166

#### Release  
Addresses release/3.6
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Pixel 3 emulator
- OS: Android 10

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

#### Additional Info
Fixes #2166. Previous call to OpenFileDialogFragment was using wildcard MIME type while caller (FileUtils) could already know the MIME type advance, causing #2166 to occur. Fixed by explicitly specifying the MIME type.

Also made call to OpenFileDialogFragment.openFileOrShow() to separate methods to prevent complaints about code duplication.

### CODE REVIEW

**Comment by VishalNehra** [comment]
Please rebase and point to 3.5.3 :)

File: app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java [hunk 1]
```diff
@@ -634,33 +634,49 @@ public void onFinish() {
             if (studioCount[0] != null) studioCount[0].cancel();
             studioCount[0] = Toast.makeText(m, m.getString(R.string.opening), Toast.LENGTH_LONG);
             studioCount[0].show();
-            OpenFileDialogFragment.Companion.openFileOrShow(
-                FileProvider.getUriForFile(m, m.getPackageName(), f),
-                "audio/*",
-                useNewStack,
-                m,
-                false);
+            openFileDialogFragmentFor(f, m, "audio/*");
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java:637]: Line number 617 to 619 are not necessary. Can remove them.

File: app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java [hunk 2]
```diff
@@ -634,33 +634,49 @@ public void onFinish() {
...
       }
     } else {
       try {
-        OpenFileDialogFragment.Companion.openFileOrShow(
-            FileProvider.getUriForFile(m, m.getPackageName(), f),
-            MimeTypes.getMimeType(f.getAbsolutePath(), false),
-            useNewStack,
-            m,
-            false);
+        openFileDialogFragmentFor(f, m);
```
Comment (VishalNehra) [inline app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java:645]: Line 645 and 641 are duplicate. The conditions can be simplified. 
For eg. 
```
else if (Icons.getTypeOfFile(f.getPath(), f.isDirectory()) == Icons.AUDIO && studio_count != 0) {
// start count down timer
} else {
openFileDialogFragmentFor(f, m);
}
```

**Review by VishalNehra — CHANGES_REQUESTED** [review]

**Review by VishalNehra — APPROVED** [review]
