### PR TITLE
Fix 1376

### LINKED ISSUE #782: Why make comparison between EMAIL_ADDRESS pattern and path then changing openmode to root?
https://github.com/TeamAmaze/AmazeFileManager/blob/bc8265249f38ae8499993993b8195f1ce95ec960/app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java#L119-L120

Why does this comparison exist? Why does it change the openmode to ROOT?

### LINKED ISSUE #1376: Can't creat or edit files or folder on root folder
Hi there,

I'm using a FairPhone2 With FairPhone Open OS 18.03.01 / Android 6.0.1

I'm actually root on this terminal, and i tied to edit my build.prop with the app.

And unfortunatly when i edit the file with Amaze, it give me an error when saving, and the files didn't change. So i've tried to create files or folders on the root folder and it's not possible any times. Is that normal? Is there a way to desactivate that if it's a security restriction?

Anyway thanks for the job done, the app is very usefull.

### LINKED ISSUE #1381: Copy failure
API 27
AVD Pixel 2

Copy 5MB file.

Logcat:
```
07-31 13:02:50.841 com.amaze.filemanager W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.support.v4.provider.DocumentFile.getUri()' on a null object reference
        at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:256)
07-31 13:02:50.842 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:320)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:486)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:387)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:260)
        at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:224)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
07-31 13:02:59.356 com.amaze.filemanager E/CopyService: Got exception checkout: /storage/emulated/0/Download/a.tar
```

### LINKED ISSUE #1447: Unable to read & write files in the root directory
Root permission has been provided, but Unable to read and write files in the directory of /data/data/app_packagename (with permission -rw--------). 
Cannot  open and copy , Cannot display the md5/sha-256 information.

I also could not rename a file from quickAccessPref[1] (Recent)

### PR DESCRIPTION
**Pull request by VishalNehra**
Fix #1376 
Also fixes duplicate '/' which traversing through root directories (not sure if there was an issue for this).

Edit:
Should also fix #1381 @EmmanuelMess please check once. 
Edit2: 
Figured I was looking into LoadListTask, also fix #782 please check and verify. 
Edit 3 (by @EmmanuelMess):
Fixes #1447

### CODE REVIEW

**Comment by TranceLove** [comment]
Because my Oneplus One died just this Sunday, verification tests had to be done on Pixel 2 emulators running 7.1.1 (temporarily rooted with directions [here](https://android.stackexchange.com/a/176400)), and Galaxy S2 running SlimLP (5.1.1).

Duplicated slash displayed at path label tested OK.

Create new file at `/system` failed with:
```
09-19 14:41:20.489 6513-6691/com.amaze.filemanager W/System.err: java.io.FileNotFoundException: /system/etc/DummyFile (Read-only file system)
        at java.io.FileOutputStream.open(Native Method)
09-19 14:41:20.490 6513-6691/com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at com.amaze.filemanager.filesystem.FileUtil.isWritable(FileUtil.java:668)
        at com.amaze.filemanager.filesystem.Operations.checkFolder(Operations.java:508)
        at com.amaze.filemanager.filesystem.Operations.access$000(Operations.java:34)
        at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:302)
        at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:198)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
    java.io.IOException: Read-only file system
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
        at java.io.File.createNewFile(File.java:948)
        at com.amaze.filemanager.filesystem.FileUtil.mkfile(FileUtil.java:562)
        at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:308)
        at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:198)
        at android.os.AsyncTask$2.call(AsyncTask.java:305)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```
Edit `/system/etc/hosts` succeeded with manually remount `/system`... did I miss anything?

**Comment by VishalNehra** [comment]
@TranceLove each operation succeeds on my device (Nexus 6P running Oreo, Magisk 16.0)
Though I should point, the crash you reported is thrown and toast also says 'Operation unsuccessful' but file is successfully created. The crash thrown is part of code {FileUtil#668} but the error is also handled by the code following it. So I suggest to check for the file created regardless of what the toast says.

> Edit /system/etc/hosts succeeded with manually remount /system... did I miss anything (that Amaze can do the remount for me)?

Yes, re-mounts are handled by Amaze.

I should say I didn't write test cases for it (can hardly find time to work on fixes). So I suggest to test of real devices.

**Comment by TranceLove** [comment]
Tested again with Oneplus 2 running Slim7 (7.1.2), create or edit files at /system both works, so functionally I can vote +1; just the error toast even when the underlying I/O succeeded is a bit confusing...

It's OK to handle this in another PR however.

**Comment by VishalNehra** [comment]
@TranceLove the execution does wait for file to get created. And I'm yet to find the cause for this race condition. But this bug was already there in master, so I think this can be worked out in a separate issue.

**Comment by TranceLove** [comment]
Then I have no further questions to ask - just need to make @EmmanuelMess happy now :)

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java [hunk 1]
```diff
@@ -668,9 +669,11 @@ public static boolean isWritable(final File file) {
             try {
                 output.close();
             } catch (IOException e) {
+                e.printStackTrace();
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java]: Is it a good idea not to do `Exception.printStackTrace()` here?

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java [hunk 2]
```diff
@@ -668,9 +669,11 @@ public static boolean isWritable(final File file) {
...
                 // do nothing.
             }
         } catch (FileNotFoundException e) {
+            e.printStackTrace();
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java]: Is it a good idea not to do `Exception.printStackTrace()` here?

File: app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java]: What's the difference?

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/filesystem/FileUtil.java]: I don't know the usage of this code apart from a call here. So I think it's better to print the whole stack trace in case operation don't complete (unlike here, when it was completed).

File: app/src/main/java/com/amaze/filemanager/ui/views/appbar/BottomBar.java [hunk 3]
```diff
@@ -333,6 +333,9 @@ public void updatePath(@NonNull final String news, boolean results, String query
         }
 
         final String oldPath = fullPathText.getText().toString();
+
+        // replace multiple occurrences of '/' with single
+        newPath = newPath.replaceAll("/{2,}", "/");
```
[the remark this answers is not in the document]
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/views/appbar/BottomBar.java]: @VishalNehra maybe you missed this comment.

[the remark this answers is not in the document]
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/ui/views/appbar/BottomBar.java]: @EmmanuelMess I didn't miss, it's just that I couldn't find time for it.
Anyways, fixed this with new commits. Please checkout.

**Comment by VishalNehra** [comment]
@TranceLove @EmmanuelMess please checkout new changes.

File: app/src/main/java/com/amaze/filemanager/ui/views/appbar/BottomBar.java [hunk 4]
```diff
@@ -9,6 +9,7 @@
 import android.support.annotation.ColorInt;
 import android.support.annotation.NonNull;
 import android.support.v4.app.Fragment;
+import android.util.Log;
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/ui/views/appbar/BottomBar.java]: This looks unused now.

**Comment by EmmanuelMess** [comment]
Fix doesn't work on rooted Motorola RAZR D1 TV XT915:
```
10-13 00:46:01.581 com.amaze.filemanager W/System.err: java.io.FileNotFoundException: /DummyFile: open failed: EROFS (Read-only file system)
10-13 00:46:01.581 com.amaze.filemanager W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:451)
10-13 00:46:01.581 com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
10-13 00:46:01.582 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.FileUtil.isWritable(FileUtil.java:668)
10-13 00:46:01.583 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.Operations.checkFolder(Operations.java:508)
10-13 00:46:01.583 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.Operations.access$000(Operations.java:34)
10-13 00:46:01.583 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:302)
10-13 00:46:01.584 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:198)
10-13 00:46:01.585 com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-13 00:46:01.585 com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-13 00:46:01.586 com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-13 00:46:01.587 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-13 00:46:01.587 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-13 00:46:01.588 com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:856)
10-13 00:46:01.589 com.amaze.filemanager W/System.err: Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
10-13 00:46:01.591 com.amaze.filemanager W/System.err:     at libcore.io.Posix.open(Native Method)
10-13 00:46:01.591 com.amaze.filemanager W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
10-13 00:46:01.591 com.amaze.filemanager W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:435)
10-13 00:46:01.592 com.amaze.filemanager W/System.err: 	... 12 more
10-13 00:46:01.593 com.amaze.filemanager W/System.err: java.io.IOException: open failed: EROFS (Read-only file system)
10-13 00:46:01.594 com.amaze.filemanager W/System.err:     at java.io.File.createNewFile(File.java:940)
10-13 00:46:01.595 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.FileUtil.mkfile(FileUtil.java:562)
10-13 00:46:01.596 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:308)
10-13 00:46:01.597 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.Operations$2.doInBackground(Operations.java:198)
10-13 00:46:01.597 com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-13 00:46:01.598 com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
10-13 00:46:01.598 com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
10-13 00:46:01.599 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
10-13 00:46:01.600 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
10-13 00:46:01.601 com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:856)
10-13 00:46:01.603 com.amaze.filemanager W/System.err: Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
10-13 00:46:01.605 com.amaze.filemanager W/System.err:     at libcore.io.Posix.open(Native Method)
10-13 00:46:01.606 com.amaze.filemanager W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
10-13 00:46:01.607 com.amaze.filemanager W/System.err:     at java.io.File.createNewFile(File.java:933)
10-13 00:46:01.607 com.amaze.filemanager W/System.err: 	... 9 more
```

**Comment by EmmanuelMess** [comment]
Got when coping file in AVD API 27 3.2 QVGA:
```
2018-10-13 00:49:22.984 com.android.systemui W/System: ClassLoader referenced unknown path: 
2018-10-13 00:49:22.994 com.amaze.filemanager W/System.err: java.io.FileNotFoundException: null/Photoshop.zip (No such file or directory)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.open0(Native Method)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.open(FileOutputStream.java:287)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.filesystem.FileUtil.isWritable(FileUtil.java:668)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:250)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:333)
2018-10-13 00:49:22.995 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:489)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:393)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:266)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:231)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-10-13 00:49:23.006 com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.support.v4.provider.DocumentFile.getUri()' on a null object reference
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:265)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:333)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:489)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:393)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:266)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:231)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-10-13 00:49:23.008 com.amaze.filemanager W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-10-13 00:49:23.008 com.amaze.filemanager E/CopyService: Got exception checkout: /storage/emulated/0/Photoshop.zip
```

**Comment by VishalNehra** [comment]
> Got when coping file in AVD API 27 3.2 QVGA:

File is created, even when there is a crash dump and an 'unsuccessful' toast. So please check for file manually

**Comment by EmmanuelMess** [comment]
About #1376: Not working on rooted Motorola RAZR D1 TV XT915 (checked for file specifically), maybe there's some other problem?
About #1381: Still not working on AVD API 27 3.2 QVGA (checked for files specifically)

**Comment by VishalNehra** [comment]
Works for me and @TranceLove 
This is the best i can currently fix it. Let's check with beta testers and confirm.
