### PR TITLE
Fixes #3733

### LINKED ISSUE #3733: `NPE` on `FileUtils#shareFiles`
## Exception
* __App Name:__ Amaze File Manager
* __Package:__ com.amaze.filemanager
* __Version:__ 3.8.5
* __User Action:__ UI Error
* __Request:__ Application crash
* __OS:__ Linux
OnePlus/OnePlus7T_EEA/OnePlus7T:12/SKQ1.211113.001/Q.202208171858:user/release-keys
12 - 31
* __Device:__ OnePlus7T
* __Model:__ HD1900
* __Product:__ OnePlus7T_EEA
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean
java.lang.String.equals(java.lang.Object)' on a null object reference
at
com.amaze.filemanager.filesystem.files.FileUtils.shareFiles(FileUtils.java:403)
at
com.amaze.filemanager.utils.MainActivityActionMode.onActionItemClicked(MainActivityActionMode.kt:302)
at
androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2709)
at
androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
at
androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
at
androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
at android.widget.AdapterView.performItemClick(AdapterView.java:352)
at android.widget.AbsListView.performItemClick(AbsListView.java:1235)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3232)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by VishnuSanal**
## Description

Refractored `FileUtils#shareFiles` & fixed NPE.

#### Issue tracker   
Fixes #3733

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [ ] Done  
  

#### Build tasks success 
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java [hunk 1]
```diff
@@ -389,26 +389,29 @@ protected void onPostExecute(String s) {
...
-  public static void shareFiles(ArrayList<File> a, Activity c, AppTheme appTheme, int fab_skin) {
+  public static void shareFiles(
+      ArrayList<File> files, Activity activity, AppTheme appTheme, int fab_skin) {
 
     ArrayList<Uri> uris = new ArrayList<>();
-    boolean b = true;
-    for (File f : a) {
-      uris.add(FileProvider.getUriForFile(c, c.getPackageName(), f));
-    }
+    boolean isGenericFileType = false;
```
Comment (VishnuSanal) [inline app/src/main/java/com/amaze/filemanager/filesystem/files/FileUtils.java:396]: please verify the logic here, just to making sure something is not broken whilst refractoring.

**Review by VishalNehra — APPROVED** [review]
