### PR TITLE
Bugfix/2910 Fix screen rotation bug

### LINKED ISSUE #2910: Failure to persist selected list items on device rotation
Failure to persist selected list items on device rotation. The bug has been present since 3.5.0 release, was working fine in 3.5 beta 2.

### PR DESCRIPTION
**Pull request by VishalNehra**
#### Issue tracker   

Fixes #2910 

#### Automatic tests

- [ ] Added test cases
  
#### Manual tests
- [x] Done  
  

#### Build tasks success  

Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by VishalNehra** [comment]
Build test apk

File: app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt [hunk 1]
```diff
@@ -0,0 +1,458 @@
...
+            item.isVisible = false
+        }
+
+        private fun showOption(id: Int, menu: Menu) {
+            val item = menu.findItem(id)
+            item.isVisible = true
+        }
+
+        fun initMenu(menu: Menu?) {
+            /*
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt:64]: Why is this commented?

File: app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt [hunk 2]
```diff
@@ -0,0 +1,458 @@
...
+import com.amaze.filemanager.ui.selection.SelectionPopupMenu.Companion.invokeSelectionDropdown
+import java.io.File
+import java.util.ArrayList
+
+class ActionModeHelper(val mainActivity: MainActivity) {
+
+    var actionModeView: View? = null
+    var actionMode: ActionMode? = null
+
+    var mActionModeCallback: ActionMode.Callback = object : ActionMode.Callback {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt:52]: Please move this to a named object (it may be in this file)

File: app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt [hunk 3]
```diff
@@ -0,0 +1,458 @@
...
+import com.amaze.filemanager.filesystem.HybridFileParcelable
+import com.amaze.filemanager.filesystem.PasteHelper
+import com.amaze.filemanager.filesystem.files.FileUtils
+import com.amaze.filemanager.ui.activities.MainActivity
+import com.amaze.filemanager.ui.dialogs.GeneralDialogCreation
+import com.amaze.filemanager.ui.selection.SelectionPopupMenu.Companion.invokeSelectionDropdown
+import java.io.File
+import java.util.ArrayList
+
+class ActionModeHelper(val mainActivity: MainActivity) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt:47]: This is not a helper, as it has a constructor, this should be the MainActivityActionMode

File: app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt [hunk 4]
```diff
@@ -191,4 +195,17 @@ class MainFragmentViewModel : ViewModel() {
             CloudHandler.CLOUD_PREFIX_BOX + "/" == currentPath ||
             CloudHandler.CLOUD_PREFIX_DROPBOX + "/" == currentPath
     }
+
+    /**
+     * Get checked items in adapter
+     */
+    fun getCheckedItems(): ArrayList<LayoutElementParcelable> {
+        val selected = ArrayList<LayoutElementParcelable>()
+        for (i in adapterListItems!!.indices) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/data/MainFragmentViewModel.kt:204]: Please remove `!!`

**Comment by EmmanuelMess** [comment]
What is "select similar"? On the dropdown on the selection actionmenu? Was that dropdown added by this PR?

File: app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt (hunk 2 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt:52]: Isn't this a named object 🤔

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt:52]: > Isn't this a named object thinking

AFAIK it is a variable assigned with an anonymous instance of a class named `ActionMode.Callback`.

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java [hunk 5]
```diff
@@ -398,30 +404,23 @@ public void toggleChecked(boolean b) {
...
-      if (itemsDigested.get(i).getChecked() == ListItem.CHECKED) {
-        selected.add(itemsDigested.get(i).elem);
-      }
-    }
-
-    return selected;
+    return mainFrag.getMainFragmentViewModel().getCheckedItems();
   }
 
   public ArrayList<ListItem> getItemsDigested() {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java:415]: This discards `@Nullable`

**Review by TranceLove — COMMENTED** [review]
Tested OK on Pixel 2 emulator running Android 11, Pixel emulator running Android 4.4
- after selecting the items and rotate the screen, the items are still selected and item count remains the same
- when nothing is selected, rotating screen doesn't change anything with the app

Other than the code improvement as suggested by @EmmanuelMess, consider it a +1.

File: app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt (hunk 2 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt:52]: This is just a one off implementation, I don't think this'll be used anywhere else. A named object of anonymous class should be fine.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/ActionModeHelper.kt]: @VishalNehra creating a class for it helps reduce the amount of the indentation and prevents leakages, as one might miss the fact that keeping a reference to `mActionModeCallback` both keeps the `MainActivityActionMode` instance and the `MainActivity` and related `Context`.

**Review by EmmanuelMess — COMMENTED** [review]
Works on my Nokia 24 M

**Review by EmmanuelMess — APPROVED** [review]
Works on my Nokia 24 M
