### PR TITLE
Fix app crash when passing an empty list of files to PasteHelper

### LINKED ISSUE #2382: IllegalArgumentException on PasteHelper constructor
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux Android 9 - 28
* __Device:__ ASUS_X00T_2
* __Model:__ ASUS_X00TD
* __Product:__ WW_X00TD
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException
at com.amaze.filemanager.filesystem.PasteHelper.<init>(PasteHelper.java:62)
at
com.amaze.filemanager.ui.fragments.MainFragment$3.onActionItemClicked(MainFragment.java:681)
at
androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2452)
at
androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:141)
at
androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
at
androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
at
androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
at
androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
at
androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
at android.view.View.performClick(View.java:6605)
at android.view.View.performClickInternal(View.java:6582)
at android.view.View.access$3100(View.java:778)
at android.view.View$PerformClick.run(View.java:25897)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6692)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by HoussemNasri**
## PR Info

Fixes #2382

#### Release  
Addresses release/3.6
  
#### Test cases
- [x] Covered
  
#### Manual testing
- [ ] Done  

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java [hunk 1]
```diff
@@ -681,9 +681,12 @@ public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
                     item.getItemId() == R.id.cpy
                         ? PasteHelper.OPERATION_COPY
                         : PasteHelper.OPERATION_CUT;
-
-                PasteHelper pasteHelper = new PasteHelper(getMainActivity(), op, copies);
-                getMainActivity().setPaste(pasteHelper);
+                // Making sure we don't cause an IllegalArgumentException
+                // when passing copies to PasteHelper
+                if(copies.length > 0){
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java:686]: Why would copies be of length 0? Why is it not null?

Comment (HoussemNasri) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java:686]: because it's created like this
```java
HybridFileParecelable[] copies = new HybridFileParecelable[checkedItems.size()];
```

**Comment by VishalNehra** [comment]
Build failure here, can you please check formatting using `./gradlew spotlessCheck` and use `./gradlew spotlessApply`

File: app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java (hunk 1 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: Still why would copies be of length 0?

Comment (HoussemNasri) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: I also have the same question, I tried to replicate the bug but I couldn't

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: Try to use the code paths to find what causes the issue.

Comment (HoussemNasri) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: Can you explain more?

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: Without replicating, you can analyze the code and the error to find where it could have happened and why.

Comment (HoussemNasri) [reply app/src/main/java/com/amaze/filemanager/ui/fragments/MainFragment.java]: After looking into the crash log I've found that the error is triggered by `onActionItemClicked()` method in `MainFragment`, the crash is a bit weird because it seems the app logic hides the action bar when there is no file selected, so there is no way `checkedItems` will be empty, but I added a check condition anyway to make sure it does not happen again.

**Review by EmmanuelMess — APPROVED** [review]

**Review by TranceLove — APPROVED** [review]
Makes sense. +1.
