### PR TITLE
Fix glide iconloading

### LINKED ISSUE #550: GIF Thumbnails not showing
Animated GIF thumbnails please. 
Love

### LINKED ISSUE #893: Loading images from cloud is broken
Images from dropbox won't load, a model must be added to support `DROPBOX://` and other similar paths.

### PR DESCRIPTION
**Pull request by VishalNehra**
Fixes image loading for cloud 
Also fixes GIF loading
Fixes #893 
Fixes #550

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    }
+
+    @Override
+    public boolean handles(String s) {
+        return s.startsWith(CloudHandler.CLOUD_PREFIX_BOX)
+                || s.startsWith(CloudHandler.CLOUD_PREFIX_DROPBOX)
+                || s.startsWith(CloudHandler.CLOUD_PREFIX_GOOGLE_DRIVE)
+                || s.startsWith(CloudHandler.CLOUD_PREFIX_ONE_DRIVE)
+                || s.startsWith("smb:/")
+                || s.startsWith("sftp:/");
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: Should be `ssh:/` instead. Sorry I should have make it into a constant...

**Comment by TranceLove** [comment]
Additionally a question: is there a limit on target image file size that thumbnail generation will be skipped? And if there is an option to turn it off? Think an user on mobile data browsing his/her photo album on Dropbox.

**Comment by TranceLove** [comment]
Getting regression as I tested, on Oneplus One running Slim7 (7.1.2).

On my storage I put adaway's apk, one folder would sometimes turned to adaway's icon as I scrolled up and down. (Look at `tmp`)

screenshot_20180513-220950

On another case, one of the files was getting a thumbnail which it should not be. It was a cpio archive placed inside a folder with mostly media files. (Look at `oggDropXPd.ini.cpio`)

screenshot_20180513-222650

Logcat didn't say anything, so can't help too much on this... only thing sure was the regression didn't happen on `master`.

File: app/src/main/java/com/amaze/filemanager/AmazeFileManagerModule.java [hunk 2]
```diff
@@ -17,5 +18,6 @@
     @Override
     public void registerComponents(Context context, Glide glide, Registry registry) {
         registry.prepend(String.class, Drawable.class, new ApkImageModelLoaderFactory(context.getPackageManager()));
+        registry.prepend(String.class, String.class, new CloudIconModelFactory(context));
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/AmazeFileManagerModule.java]: That second `String.class` should probably be `Bitmap.class` (also, check the generic type inference missing in `CloudIconModelLoader`).

File: app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+        this.context = context;
+    }
+
+    @Nullable
+    @Override
+    public LoadData<String> buildLoadData(String s, int width, int height, Options options) {
+        // we put key as current time since we're not disk caching the images for cloud,
+        // as there is no way to differentiate input streams returned by different cloud services
+        // for future instances and they don't expose concrete paths either
+        return new LoadData(new ObjectKey(System.currentTimeMillis()), new CloudIconDataFetcher(context, s));
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: Type inferance missing, please use `new LoadData<>(...);`.

Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: `new ObjectKey(System.currentTimeMillis())`?!! This is be a key for caching, and I already told you about this error.

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: Left a comment about it there.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: You [said](https://github.com/TeamAmaze/AmazeFileManager/issues/893#issuecomment-388588538): 

> Thank you, your last advice about loadData handling all the heavy work for icon loading really helped as I seem to have skipped it while reading documentation.
> I've made a PR which should fix this issue.

Not addressing caching.

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: Comment above this line of code in program.

File: app/src/main/java/com/amaze/filemanager/utils/GlideConstants.java [hunk 4]
```diff
@@ -7,7 +7,7 @@
 
 public class GlideConstants {
 
-    public static final int MAX_PRELOAD_FILES = 50;
-    public static final int MAX_PRELOAD_APPSADAPTER = 100;
+    public static final int MAX_PRELOAD_FILES = 10;
+    public static final int MAX_PRELOAD_APPSADAPTER = 50;
```
[the remark this answers is not in the document]
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/utils/GlideConstants.java]: Decreased it while testing, will bump it up again.

**Comment by VishalNehra** [comment]
@TranceLove no problems while getting 4-5 Mb file icons as the API support fetching downsampled icons using ````getThumbnail```` instead of ```getInputStream````
As for the folder icon, it happens when we quickly swipe through the list. I'm yet to pinpoint the cause... Willing to improve it as a separate issue.

File: app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java (hunk 3 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: I'm blind :smile:. 

> we put key as current time since we're not disk caching the images for cloud

We are memory caching.

> as there is no way to differentiate input streams returned by different cloud services

Can't you use the string as a unique identifier? Is it random? Doesn't the server provide a hash?

**Comment by TranceLove** [comment]
> @TranceLove no problems while getting 4-5 Mb file icons as the API support fetching downsampled icons using `getThumbnail` instead of `getInputStream`

How about SMB/SFTP files? I saw you are [using the relevant API to fetch files directly](https://github.com/TeamAmaze/AmazeFileManager/blob/bf8ed86d0ce553cab6a6cdd781f597a4970afcf2/app/src/main/java/com/amaze/filemanager/utils/cloud/CloudUtil.java#L271-L300).

SMB is forgivable since nobody would be using SMB/CIFS across the Internet, but SFTP will - I'm one of them, even I rarely do SCP/SFTP over mobile data.

**Comment by VishalNehra** [comment]
@TranceLove what's your point? What else do you suggest for fetching icon for SFTP or SMB other than from the input streams.

**Comment by TranceLove** [comment]
> @TranceLove what's your point? What else do you suggest for fetching icon for SFTP or SMB other than from the input streams.

It would be nice if I can have an option to switch off fetching thumbnails for files on remote servers. However it can be done on a separate PR.

**Comment by VishalNehra** [comment]
@TranceLove we do have an option for that in settings

File: app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java (hunk 3 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: No, and no.

**Comment by VishalNehra** [comment]
Please checkout dfc5e84

**Comment by TranceLove** [comment]
Saw my requested changes are here now.

One other glitch, but may not be related to this PR. On loading thumbnails from a SSH server, if the folder has many images (< 200KB each though) app will crash after scrolling the list for a while.

Logcat had a lot to say... but this one got my attention:
```
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
        at net.schmizz.sshj.transport.TransportImpl.write(TransportImpl.java:451)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:102)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream$DataBuffer.flush(ChannelOutputStream.java:70)
        at net.schmizz.sshj.connection.channel.ChannelOutputStream.flush(ChannelOutputStream.java:182)
        at net.schmizz.sshj.sftp.SFTPEngine.transmit(SFTPEngine.java:297)
        at net.schmizz.sshj.sftp.SFTPEngine.request(SFTPEngine.java:130)
        at net.schmizz.sshj.sftp.RemoteResource.close(RemoteResource.java:53)
        at com.amaze.filemanager.utils.cloud.CloudUtil$3$1.close(CloudUtil.java:285)
        at com.amaze.filemanager.utils.glide.CloudIconDataFetcher.cancel(CloudIconDataFetcher.java:54)
        at com.bumptech.glide.load.engine.SourceGenerator.cancel(SourceGenerator.java:99)
        at com.bumptech.glide.load.engine.DecodeJob.cancel(DecodeJob.java:212)
        at com.bumptech.glide.load.engine.EngineJob.cancel(EngineJob.java:182)
        at com.bumptech.glide.load.engine.EngineJob.removeCallback(EngineJob.java:143)
        at com.bumptech.glide.load.engine.Engine$LoadStatus.cancel(Engine.java:356)
        at com.bumptech.glide.request.SingleRequest.cancel(SingleRequest.java:290)
        at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:321)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndMaybeRecycle(RequestTracker.java:73)
        at com.bumptech.glide.manager.RequestTracker.clearRemoveAndRecycle(RequestTracker.java:60)
        at com.bumptech.glide.RequestManager.untrack(RequestManager.java:623)
        at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:591)
        at com.bumptech.glide.RequestManager.clear(RequestManager.java:579)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:616)
        at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:678)
        at com.amaze.filemanager.adapters.RecyclerAdapter.showThumbnailWithBackground(RecyclerAdapter.java:827)
        at com.amaze.filemanager.adapters.RecyclerAdapter.onBindViewHolder(RecyclerAdapter.java:553)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```

Tested on Oneplus One running Slim7 (7.1.2).

File: app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java (hunk 3 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: Doesn't the server provide a hash?

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/utils/glide/CloudIconModelLoader.java]: I am not familiar with CloudRail in any way, but I noticed that in `CloudStorage` there is a way of getting metadata:

```java
CloudMetaData getMetadata(String var1);
```

In `CloudMetaData` there is:
```java
    private String path;
    private String name;
    private int size;
    private boolean folder;
    private Long modifiedAt;
    private ImageMetaData imageMetaData;
    [...]
    public int hashCode() {
        [...]
        return result;
    }

```
That hash should be unique enough.

**Comment by VishalNehra** [comment]
@TranceLove please test with latest changes.
Also tried fixing the random image shown in directory icon, it won't show now but the icon itself disappears sometimes.

File: app/src/main/java/com/amaze/filemanager/adapters/glide/RecyclerPreloadModelProvider.java [hunk 5]
```diff
@@ -43,17 +43,14 @@ public RecyclerPreloadModelProvider(@NonNull Fragment fragment, @NonNull List<Ic
     @Override
     @Nullable
     public RequestBuilder<Drawable> getPreloadRequestBuilder(IconDataParcelable iconData) {
-        if(!showThumbs) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/glide/RecyclerPreloadModelProvider.java]: There is a setting to only show resource icons, not thumbs, shouldn't the code for that be present here?

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java [hunk 6]
```diff
@@ -697,8 +730,12 @@ public void onBindViewHolder(final RecyclerView.ViewHolder vholder, int p) {
                                 iconBackground.setBackgroundColor(genericColor);
                                 break;
                             case Icons.APK:
+                                if (!getBoolean(PREFERENCE_SHOW_THUMB))
+                                    iconBackground.setBackgroundColor(apkColor);
+                                break;
                             case Icons.IMAGE:
-                                //While these are loading or if they fail, color has to be set (done in showRoundedThumbnail()).
+                                if (!getBoolean(PREFERENCE_SHOW_THUMB))
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java]: Please use standard brackets.

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java [hunk 7]
```diff
@@ -835,16 +881,19 @@ private void showRoundedThumbnail(ItemViewHolder viewHolder, IconDataParcelable
 
         View iconBackground = getBoolean(PREFERENCE_USE_CIRCULAR_IMAGES)? viewHolder.genericIcon:viewHolder.iconLayout;
 
-        iconBackground.setBackgroundColor(iconSkinColor);
+        //iconBackground.setBackgroundColor(iconSkinColor);
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java]: Commented code, explain or delete.

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java [hunk 8]
```diff
@@ -835,16 +881,19 @@ private void showRoundedThumbnail(ItemViewHolder viewHolder, IconDataParcelable
...
-        modelProvider.getPreloadRequestBuilder(iconData).listener(new RequestListener<Drawable>() {
+        RequestListener<Drawable> requestListener = new RequestListener<Drawable>() {
             @Override
             public boolean onLoadFailed(@Nullable GlideException e, Object model, Target target, boolean isFirstResource) {
                 iconBackground.setBackgroundColor(grey_color);
-                GlideApp.with(mainFrag).load(R.drawable.ic_broken_image_white_24dp).into(viewHolder.genericIcon);
+                new Handler(msg -> {
+                    GlideApp.with(mainFrag).load(R.drawable.ic_broken_image_white_24dp).into(viewHolder.genericIcon);
+                    return false;
+                }).obtainMessage().sendToTarget();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java]: Where are you setting the target? Have you tested this code? Why use a Handler?

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java [hunk 9]
```diff
@@ -440,7 +442,7 @@ public int getItemViewType(int position) {
                     sizeProvider.addView(VIEW_THUMB, view.findViewById(R.id.icon_thumb));
                 }
 
-                sizeProvider.closeOffAddition();
+                //sizeProvider.closeOffAddition();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java]: Commented code, explain or delete.

File: app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java (hunk 8 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/RecyclerAdapter.java]: Yes I've tested. Handlers are necessary otherwise there was an error to not post another load in listeners.

File: app/src/main/java/com/amaze/filemanager/adapters/glide/RecyclerPreloadModelProvider.java (hunk 5 above)
Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/glide/RecyclerPreloadModelProvider.java]: The code for that is present in RecyclerAdapter. It's not necessary here.

**Comment by TranceLove** [comment]
> @TranceLove please test with latest changes.
Also tried fixing the random image shown in directory icon, it won't show now but the icon itself disappears sometimes.

Verified with Oneplus One running Slim7 (7.1.2) and Galaxy S2 running SlimLP (5.1.1), crash problem and wrong icon problems are fixed. Not sure if I can vote +1 now because the mentioned glitch did happened sometimes (for my cases, seems only on folders though), but I'm already impressed.

**Comment by VishalNehra** [comment]
@EmmanuelMess Unable to get ````CloudMetaData#hashCode```` to work. Refer to [this issue](https://github.com/CloudRail/cloudrail-si-android-sdk/issues/112).
Also not sure how to get hash code for SFTP files will be needing help from @TranceLove 
I think we can work on it later in a separate issue.

**Comment by EmmanuelMess** [comment]
@VishalNehra I think you can still hack a solution for now, if you can instance a `CloudMetaData` object, use the directory, name and size to create a temporary hash function.

File: app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java [hunk 10]
```diff
@@ -64,6 +78,7 @@ public IconDataParcelable(Parcel im) {
         image = im.readInt();
         loadingImage = im.readInt();
         isImageBroken = im.readInt() == 1;
+        hashCode = im.readInt();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java]: What if `hashCode` was null?

File: app/src/main/java/com/amaze/filemanager/adapters/data/LayoutElementParcelable.java [hunk 11]
```diff
@@ -50,18 +50,43 @@
...
         filetype = Icons.getTypeOfFile(path, isDirectory);
         @DrawableRes int fallbackIcon = Icons.loadMimeIcon(path, isDirectory);
-
+        this.mode = openMode;
         if(useThumbs) {
-            if (filetype == Icons.IMAGE || filetype == Icons.VIDEO || filetype == Icons.APK) {
-                this.iconData = new IconDataParcelable(IconDataParcelable.IMAGE_FROMFILE, path, fallbackIcon);
-            } else {
-                this.iconData = new IconDataParcelable(IconDataParcelable.IMAGE_RES, fallbackIcon);
+            switch (mode) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/adapters/data/LayoutElementParcelable.java]: This seems incomplete, is this incomplete?

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/data/LayoutElementParcelable.java]: This is complete and working as intended.

File: app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java (hunk 10 above)
Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java]: What are you reading in `im.readInt()` then?

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java]: It'll reference hashCode  to null in case hashCode was null. We don't save hashcode for general file types, but only for cloud storages. So in case of cloud storage if hashcode was null then icon won't load up. In general file types, hashcode is not utilized anywhere so nothing will happen.
I'll better document this.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java]: `readInt ()` [returns primitive int](https://developer.android.com/reference/android/os/Parcel#readint), can't return null.

Comment (VishalNehra) [reply app/src/main/java/com/amaze/filemanager/adapters/data/IconDataParcelable.java]: I've put in a fix in another commit.

**Comment by EmmanuelMess** [comment]
I feel that having the hashcode everywhere and passing the entire `IconDataParcelable` (instead of a specific, non-parcelable, object) to get a cloud image is a bit confusing, but I'l settle with this.

**Comment by VishalNehra** [comment]
Caching for cloud is still giving problems that I'm unable to solve.

````06-04 16:01:10.654 13882-13882/com.amaze.filemanager W/Glide: Load failed for com.amaze.filemanager.adapters.data.IconDataParcelable@c1df014 with size [126x126]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    com.bumptech.glide.Registry$NoSourceEncoderAvailableException(Failed to find source encoder for data class: class android.graphics.Bitmap)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.graphics.Bitmap
06-04 16:01:10.654 13882-14111/com.amaze.filemanager E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.graphics.Bitmap
        at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:572)
        at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:241)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:269)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
````

I'm considering reverting back to ````DiskCacheStretegy#NONE```` until we have a clear fix  because this is  unreasonably pushing release dates further.

**Comment by EmmanuelMess** [comment]
@VishalNehra Ok, remove caching for now. But do create an issue afterwards, so we don't forget we did.

**Comment by VishalNehra** [comment]
This PR ready to be merged then. Please approve of new changes.

**Comment by TranceLove** [comment]
Without the icon hashcode work I'm happy with the changeset then. I'd vote a +1.
