### PR TITLE
Null check of ApplicationInfo.sourceDir

### LINKED ISSUE #1604: App manager causes crash
Im using a rooted OnePlus 3 with Android Pie (LineageOS 16) and starting the app manager causes amaze to crash with the following error:

```
FATAL EXCEPTION: ModernAsyncTask #1
Process: com.amaze.filemanager, PID: 27309
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:58)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:26)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

### LINKED ISSUE #2127: Crash on AppListLoader
**Smartphone:**
- Device: mata
- OS: Linux Android 10 - 29
- Rooted: Maybe
- Version: 3.5.1
### Stack traces:
**Trace:**
```java
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:78)
	at com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:46)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```
<details><summary><b>Raw mail</b></summary><p>
```json
{
  "request": "Application crash",
  "user_action": "UI Error",
  "product": "mata",
  "package": "com.amaze.filemanager",
  "os": "Linux Android 10 - 29",
  "model": "PH-1",
  "time": "2020-12-09 16:14",
  "version": "3.5.1",
  "device": "mata",
  "exceptions": "[java.lang.RuntimeException: An error occurred while executing doInBackground()\n\tat androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)\n\tat java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)\n\tat java.util.concurrent.FutureTask.setException(FutureTask.java:252)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:271)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:919)\nCaused by: java.lang.NullPointerException\n\tat java.io.File.<init>(File.java:283)\n\tat com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:78)\n\tat com.amaze.filemanager.asynchronous.loaders.AppListLoader.loadInBackground(AppListLoader.java:46)\n\tat androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)\n\tat androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)\n\tat androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)\n\tat androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\t... 3 more\n]",
  "user_comment": ""
}
```

### PR DESCRIPTION
**Pull request by TranceLove**
#### Issue tracker   
Fixes will automatically close the related issue

Fixes #1604
Fixes #2127

#### Release  
Addresses release/3.5
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [ ] Done  
  
If yes,  
- Device:
- OS:

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Review by VishalNehra — APPROVED** [review]

File: app/src/main/java/com/amaze/filemanager/asynchronous/loaders/AppListLoader.java [hunk 1]
```diff
@@ -75,35 +77,39 @@ public AppsDataPair loadInBackground() {
...
-              sourceDir.lastModified(),
-              null);
-
-      mApps.first.add(elem);
-
-      Collections.sort(mApps.first, new AppDataParcelable.AppDataSorter(sortBy, asc));
-
-      for (AppDataParcelable p : mApps.first) {
-        mApps.second.add(p.path);
+      if (object.sourceDir != null) {
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/asynchronous/loaders/AppListLoader.java:80]: Invert the if to "if(object.sourceDir == null) { <log> continue;}" to reduce indentation level.

**Review by EmmanuelMess — CHANGES_REQUESTED** [review]

**Review by EmmanuelMess — APPROVED** [review]

**Comment by EmmanuelMess** [comment]
This should go to hotfix/1.5.2

**Review by VishalNehra — APPROVED** [review]

**Review by VishalNehra — APPROVED** [review]
