### PR TITLE
SftpConnectDialog and SshConnectionPool fixes

### LINKED ISSUE #2220: SFTP does not reconnect after closing the app
**Describe the bug**
When I create an SFTP connection, Amaze correctly connects to the server and shows the directory listing.
After closing Amaze, when I click on the previously created SFTP connection, an empty directory listing is shown instead.
I cannot delete the connection either, as when I click on the delete button, nothing happens. So I'm stuck with a non-working connection.

**To Reproduce**
1. Create an SFTP connection
2. Notice that the SFTP directory listing is OK
3. Close Amaze (I close it by clicking on the square multitasking button and swiping Amaze out of it)
4. Open Amaze
5. Click on the previously created SFTP connection
6. Notice that the directory listing is empty

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 7
 - OS: LineageOS 17.1 (Android 10)
 - Rooted: No
 - Version: 3.5.3 (But 3.5.2 and 3.5.1 also show the same problem. I haven't tested older versions)

**Additional context**

### LINKED ISSUE #2295: Entering hyphen in SFTP dialog port field leads to crash
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.3
* __OS:__ Linux
lge/judyln_lao_com/judyln:9/PKQ1.181105.001/191281829b7c4.FGN:user/release-keys
9 - 28
* __Device:__ judyln
* __Model:__ LM-G710
* __Product:__ judyln_lao_com
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: "-"
at java.lang.Integer.parseInt(Integer.java:607)
at java.lang.Integer.parseInt(Integer.java:650)
at
com.amaze.filemanager.ui.dialogs.SftpConnectDialog$1.afterTextChanged(SftpConnectDialog.java:357)
at android.widget.TextView.sendAfterTextChanged(TextView.java:10043)
at
android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12908)
at
android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1273)
at
android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
at
android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
at
android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:36)
at
android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:370)
at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:71)
at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:479)
at
android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:148)
at android.widget.TextView.doKeyDown(TextView.java:7929)
at android.widget.TextView.onKeyDown(TextView.java:7706)
at android.view.KeyEvent.dispatch(KeyEvent.java:2698)
at android.view.View.dispatchKeyEvent(View.java:12485)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:401)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1967)
at
com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:444)
at
com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1844)
at android.app.Dialog.dispatchKeyEvent(Dialog.java:888)
at
com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:358)
at
android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5347)
at
android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5215)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
at
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
at
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4801)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4858)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
at
android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4679)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4645)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4653)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4626)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7434)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7403)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7364)
at
android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4366)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6854)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

```
</details>
<hr>

### PR DESCRIPTION
**Pull request by TranceLove**
- Changed SftpConnectDialog to Kotlin and adopt view binding instead of `findViewById` (#2101)
- Fix SshConnectionPool on getting information for SSH URIs that have default path set
- Display error log on fetching SSH keys (host/auth) only on debug builds

#### Issue tracker   
Fixes will automatically close the related issue

Fixes #2295
Fixes #2220 

#### Release  
Addresses release/
  
#### Test cases
- [ ] Covered
  
#### Manual testing
- [x] Done  
  
If yes,  
- Device: Pixel 2 emulator
- OS: Android 11

#### Build tasks success  
Successfully running following tasks on local 
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

**Comment by EmmanuelMess** [comment]
```
java.lang.NumberFormatException: For input string: "2285631265"
	at java.lang.Integer.parseInt(Integer.java:618)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.amaze.filemanager.ui.dialogs.SftpConnectDialog$1.afterTextChanged(SftpConnectDialog.java:367)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:10594)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13581)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
	at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:131)
	at android.widget.TextView.doKeyDown(TextView.java:8466)
	at android.widget.TextView.onKeyDown(TextView.java:8240)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2842)
	at android.view.View.dispatchKeyEvent(View.java:14247)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:491)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1959)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:476)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1861)
	at android.app.Dialog.dispatchKeyEvent(Dialog.java:823)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5947)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5815)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:5075)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

File: app/src/main/java/com/amaze/filemanager/ui/dialogs/SftpConnectDialog.java [hunk 1]
```diff
@@ -362,10 +363,8 @@ public Dialog onCreateDialog(Bundle savedInstanceState) {
         new SimpleTextWatcher() {
           @Override
           public void afterTextChanged(Editable s) {
-            int port =
-                portET.getText().toString().length() > 0
-                    ? Integer.parseInt(portET.getText().toString())
-                    : -1;
+            String v = portET.getText().toString();
```
Comment (EmmanuelMess) [inline app/src/main/java/com/amaze/filemanager/ui/dialogs/SftpConnectDialog.java:366]: Please use sensible variable names.

**Review by VishalNehra — DISMISSED** [review]

**Review by VishalNehra — APPROVED** [review]

**Review by EmmanuelMess — APPROVED** [review]
Fixes issues and code is decent
