### PR TITLE
Hack to fix a unmarshaller crash in CustomNavigationView.SaveState on Marshmallow

### LINKED ISSUE #1101: Crash when opening app after being paused
```
com.amaze.filemanager E/AndroidRuntime: FATAL EXCEPTION: main
                                        Process: com.amaze.filemanager, PID: 12228
                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.NavigationView$SavedState
                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                            at android.os.Looper.loop(Looper.java:148)
                                            at android.app.ActivityThread.main(ActivityThread.java:5443)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                         Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.NavigationView$SavedState
                                            at android.os.Parcel.readParcelableCreator(Parcel.java:2432)
                                            at android.os.Parcel.readParcelable(Parcel.java:2358)
                                            at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
                                            at android.view.View$BaseSavedState.<init>(View.java:21467)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState.<init>(CustomNavigationView.java:0)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState.<init>(CustomNavigationView.java:0)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState$1.createFromParcel(CustomNavigationView.java:116)
                                            at com.amaze.filemanager.ui.views.drawer.CustomNavigationView$SavedState$1.createFromParcel(CustomNavigationView.java:114)
                                            at android.os.Parcel.readParcelable(Parcel.java:2367)
                                            at android.os.Parcel.readValue(Parcel.java:2264)
                                            at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
                                            at android.os.Parcel.readSparseArray(Parcel.java:1967)
                                            at android.os.Parcel.readValue(Parcel.java:2321)
                                            at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                            at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
                                            at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2033)
                                            at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
                                            at android.app.Activity.performRestoreInstanceState(Activity.java:963)
                                            at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1186)
                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2399)
                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                            at android.os.Looper.loop(Looper.java:148) 
                                            at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                            at java.lang.reflect.Method.invoke(Native Method) 
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

### PR DESCRIPTION
**Pull request by EmmanuelMess**
Hack to fix a unmarshaller crash in CustomNavigationView.SaveState on Marshmallow.
Fix #1101.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/views/drawer/CustomNavigationView.java [hunk 1]
```diff
@@ -91,6 +104,20 @@ public void onRestoreInstanceState(Parcelable state) {
...
+     * This is a hack, when the SavedState class is unmarshalled a "ClassNotFoundException"
+     * will be thrown (the actual class not found is "android.support.design.widget.NavigationView$SavedState")
+     * and I seem to only be able to replicate on Marshmallow.
+     * Trying to find the class and returning false if Class.forName() throws "ClassNotFoundException"
+     * doesn't work because the class seems to have been loaded with the current loader
+     * (not the one the unmarshaller uses); of course I have no idea of what any of this means so
+     * I could be wrong.
+     * For the crash see https://github.com/TeamAmaze/AmazeFileManager/issues/1101.
+     */
+    public boolean doesNavigationView$SavedStateExist() {
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/ui/views/drawer/CustomNavigationView.java]: I have reservations on having dollar signs in method names, as such naming convention is usually used by generated code - e.g. `Foo$Bar.class`, `Foo$1.class`, or private methods available between inner class and its enclosing class - as read from [here](https://stackoverflow.com/questions/7578155/meanings-of-dollar-sign-in-java-method-descriptor).

While Dalvik is not strictly JVM (ala Hotspot), and it is perfectly legal syntax, I'd prevent using dollar signs in my Java code to prevent any problem that may be caused.

I prefer name it `isNavigationView_SavedStateExist()`.

Comment (EmmanuelMess) [reply app/src/main/java/com/amaze/filemanager/ui/views/drawer/CustomNavigationView.java]: Done, but I despise '_' so I just removed the '$'.
