### PR TITLE
Fix open with dialog glitch

### LINKED ISSUE #3009: Glitch in open with dialog
https://user-images.githubusercontent.com/50027064/141356569-b44d240c-596a-45fd-85bb-6cacc0367de8.mp4

The dialog option fluctuate alot & not smooth as normal android dialogs.

(video credits @shuvashish76 :D)

### PR DESCRIPTION
**Pull request by VishnuSanal**
#### Issue tracker   
Fixes #3009 

#### Automatic tests
- [ ] Added test cases
  
#### Manual tests
- [x] Done  

#### Build tasks success  
Successfully running following tasks on local:
- [x] `./gradlew assembledebug`
- [x] `./gradlew spotlessCheck`

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/ui/base/BaseBottomSheetFragment.kt [hunk 1]
```diff
@@ -23,39 +23,16 @@ package com.amaze.filemanager.ui.base
...
-                    }
-
-                    override fun onSlide(bottomSheet: View, slideOffset: Float) {
-                        // do nothing
-                    }
-                })
-            }
-        }
-        return dialog
+        return super.onCreateDialog(savedInstanceState) as BottomSheetDialog
```
Comment (VishnuSanal) [inline app/src/main/java/com/amaze/filemanager/ui/base/BaseBottomSheetFragment.kt:35]: Will this break the UX on TV? ;(

**Comment by VishalNehra** [comment]
Build test apk

**Review by VishalNehra — APPROVED** [review]
