### PR TITLE
Fix respecting hidden files while using sftp

### LINKED ISSUE #1601: sftp connections do not honor "show hidden files"
hidden files in an sftp connection are always shown regardless of whether I have "show hidden files" enabled.
This seems like the same problem that was previously fixed for SMB connections:
https://github.com/TeamAmaze/AmazeFileManager/issues/534

### PR DESCRIPTION
**Pull request by marcinadd**
I have fixed #1601 in simple way. 
Tested on:
Samsung Galaxy S4 Android 9.0 and it works perfectly.

### CODE REVIEW

File: app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java [hunk 1]
```diff
@@ -26,6 +27,7 @@
 import android.provider.MediaStore;
 import android.support.v4.util.Pair;
 import android.text.format.Formatter;
+import android.util.Log;
```
Comment (TranceLove) [inline app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java]: Redundant import.

Comment (marcinadd) [reply app/src/main/java/com/amaze/filemanager/asynchronous/asynctasks/LoadFilesListTask.java]: Fixed

**Comment by TranceLove** [comment]
Two ticks, merging.
